openapi: 3.0.3
info:
  title: Схемы enum ответов API шлюза опросов
  description: Схемы enum ответов API шлюза объявлений
  version: 1.0.0
servers:
  - url: 'https://localhost:8080'
paths:
  
components:
  schemas:
    createSurveyResponses:
      type: string
      enum:
        # 201
        - created
        # 401
        - unauthorized
        # 403
        - createSurveyForbidden
        # 409
        - votingClosesBeforeAnnouncementPublication
      description: >
        Ответы:
          created - Опрос создан
          unauthorized - 
          createSurveyForbidden - Пользователь не имеет права создать опрос
          votingClosesBeforeAnnouncementPublication - Срок окончания голосования наступит до момента публикации объявления
    
    getSurveyDetailsResponses:
      type: string
      enum:
        # 200
        - ok
        # 400
        - incorrectIdentifierFormat
        # 401
        - unauthorized
        # 403
        - detailsAccessForbidden
        # 404
        - surveyDoesNotExist
        # 409
        - announcementWithSurveyNotYetPublished
      description: >
        Ответы:
          ok - Ок
          incorrectIdentifierFormat - Некорректный формат идентификатора
          unauthorized - 
          detailsAccessForbidden - Пользователь не имеет права просмотреть подробности этого опроса
          surveyDoesNotExist - Опрос не существует
          announcementWithSurveyNotYetPublished - Объявление с опросом еще не опубликовано

    closeSurveyResponses:
      type: string
      enum:
        # 200
        - ok
        # 400
        - incorrectIdentifierFormat
        # 401
        - unauthorized
        # 403
        - surveyClosingForbidden
        # 404
        - surveyDoesNotExist
        # 409
        - surveyAlreadyClosed
        - announcementWithSurveyNotYetPublished
      description: >
        Ответы:
          ok - Ок
          incorrectIdentifierFormat - Некорректный формат идентификатора
          unauthorized - 
          surveyClosingForbidden - Пользователь не имеет права закрыть этот опрос
          surveyDoesNotExist - Опрос не существует
          surveyAlreadyClosed - Опрос уже закрыт
          announcementWithSurveyNotYetPublished - Объявление с опросом еще не опубликовано
    
    getSurveysResultsResponses:
      type: string
      enum:
        # 200
        - ok
        # 400
        - incorrectIdentifierFormat
        # 401
        - unauthorized
        # 403
        - surveyResultsAccessForbidden
        # 404
        - surveyDoesNotExist
        # 409
        - announcementWithSurveyNotYetPublished
      description: >
        Ответы:
          ok - Ок
          incorrectIdentifierFormat - Некорректный формат идентификатора
          unauthorized - 
          surveyResultsAccessForbidden - Пользователь не имеет права получить результаты этого опроса
          surveyDoesNotExist - Опрос не существует
          announcementWithSurveyNotYetPublished - Объявление с опросом еще не опубликовано

    downloadSurveyResultsResponses:
      type: string
      enum:
        # 200
        - ok
        # 400
        - incorrectIdentifierFormat
        # 401
        - unauthorized
        # 403
        - surveyResultsDownloadingForbidden
        # 404
        - surveyDoesNotExist
        # 409
        - announcementWithSurveyNotYetPublished
      description: >
        Ответы:
          ok - Ок
          incorrectIdentifierFormat - Некорректный формат идентификатора
          unauthorized - 
          surveyResultsDownloadingForbidden - Пользователь не имеет права выгрузить результаты этого опроса
          surveyDoesNotExist - Опрос не существует
          announcementWithSurveyNotYetPublished - Объявление с опросом еще не опубликовано

    voteInSurveyResponses:
      type: string
      enum:
        # 200
        - ok
        # 400
        - incorrectIdentifierFormat
        # 401
        - unauthorized
        # 403
        - votingForbidden
        # 404
        - surveyDoesNotExist
        - questionDoesNotExist
        - answerDoesNotExist
        # 409
        - surveyClosed
        - announcementWithSurveyNotYetPublished
        - answerAlreadyVoted
        - cannotSelectMultipleAnswersInSingleChoiceQuestion
        - selectedQuestionsBelongToDifferentSurveys
        - selectedAnswersBelongToDifferentQuestions
      description: >
        Ответы: 
          ok - Ок 
          incorrectIdentifierFormat - Некорректный формат идентификатора
          unauthorized - 
          votingForbidden - Пользователь не имеет права голосовать в опросе
          surveyDoesNotExist - Опрос не существует
          questionDoesNotExist - Вопрос не существует
          answerDoesNotExist - Вариант ответа не существует
          surveyClosed - Опрос закрыт
          announcementWithSurveyNotYetPublished - Объявление с опросом еще не опубликовано
          surveyAlreadyVoted - Голос в опросе уже отдан
          cannotSelectMultipleAnswersInSingleChoiceQuestion - В вопросе с единственным выбором нельзя выбрать несколько вариантов ответов
          selectedQuestionsBelongToDifferentSurveys - Перечисленные вопросы относятся к разным опросам
          selectedAnswersBelongToDifferentQuestions - Перечисленные варианты ответов относятся к разным вопросам

    cancelVoteInQuestionResponses:
      type: string
      enum:
        # 200
        - ok
        # 400
        - incorrectIdentifierFormat
        # 401
        - unauthorized
        # 403
        - votingForbidden
        # 404
        - questionDoesNotExist
        # 409
        - surveyClosed
        - surveyNotVoted
      description: >
        Ответы:
          ok - Ок
          incorrectIdentifierFormat - Некорректный формат идентификатора
          unauthorized - 
          votingForbidden - Пользователь не имеет права голосовать в этом опросе
          questionDoesNotExist - Вопрос не существует 
          surveyClosed - Опрос закрыт
          surveyNotVoted - Пользователь не проголосовал в вопросе

    
