@startuml
'https://plantuml.com/class-diagram

' A <|-- B : отдел B входит в состав отдела A (отдел B руководит отделом A)
' A <-- B : отдел B подчиняется отделу A (отдел A руководит отделом B)

left to right direction

hide methods
'hide members

entity "Университет" as university {}





entity "Руководство" as management
hide management members
' todo определиться со стрелкой
university <|-- management

    entity "Ректор" as rector
    hide rector members
    university <|-- rector
    '    rectory <|-- rector
    '    academicCouncil <|-- rector

    entity "Ректорат" as rectory {
        + Ректор
    }
'    management <|-- rectory
    rector <-- rectory

    entity "Ученый совет" as academicCouncil {
        + {field} Председатель (ректор)
    }
    management <|-- academicCouncil

    entity "Проректоры" as viceRectors
    hide viceRectors members
    rectory <|-- viceRectors

        entity "Проректор по учебной работе" as viceRectorForAcademicAffairs
        hide viceRectorForAcademicAffairs members
        viceRectors <|-- viceRectorForAcademicAffairs

        entity "Проректор по приему в вуз и международной деятельности" as viceRectorForAdmissionsAndInternationalActivities
        hide viceRectorForAdmissionsAndInternationalActivities members
        viceRectors <|-- viceRectorForAdmissionsAndInternationalActivities

        entity "Проректор по научной работе и инновациям" as viceRectorForResearchAndInnovations
        hide viceRectorForResearchAndInnovations members
        viceRectors <|-- viceRectorForResearchAndInnovations

        entity "Проректор по воспитательной работе и связям с общественностью" as viceRectorForEducationalWorkAndPublicRelations
        hide viceRectorForEducationalWorkAndPublicRelations members
        viceRectors <|-- viceRectorForEducationalWorkAndPublicRelations

        entity "Проректор по инфраструктурному развитию и информатизации" as viceRectorForInfrastructureDevelopmentAndInformatization
        hide viceRectorForInfrastructureDevelopmentAndInformatization members
        viceRectors <|-- viceRectorForInfrastructureDevelopmentAndInformatization

        entity "Проректор по организационно-правовым вопросам" as viceRectorForOrganizationalAndLegalAffairs
        hide viceRectorForOrganizationalAndLegalAffairs members
        viceRectors <|-- viceRectorForOrganizationalAndLegalAffairs

        entity "Проректор по финансовоэкономическим вопросам" as viceRectorForFinancialAndEconomicAffairs
        hide viceRectorForFinancialAndEconomicAffairs members
        viceRectors <|-- viceRectorForFinancialAndEconomicAffairs

    entity "Директора институтов и деканы факультетов" as directorsAndDeans
    hide directorsAndDeans members
    rectory <|-- directorsAndDeans
    academicCouncil <|-- directorsAndDeans

        entity "Директор института экономики и права" as instituteOfEconomicsAndLawDirector
        hide instituteOfEconomicsAndLawDirector members
        directorsAndDeans <|-- instituteOfEconomicsAndLawDirector

        entity "Директор института информационных технологий и коммуникаций" as instituteOfInformationTechnologiesAndCommunicationsDirector
        hide instituteOfInformationTechnologiesAndCommunicationsDirector members
        directorsAndDeans <|-- instituteOfInformationTechnologiesAndCommunicationsDirector

        entity "Директор института морских технологий, энергетики и транспорта" as instituteOfMarineTechnologiesEnergyAndTransportDirector
        hide instituteOfMarineTechnologiesEnergyAndTransportDirector members
        directorsAndDeans <|-- instituteOfMarineTechnologiesEnergyAndTransportDirector

        entity "Директор института нефти и газа" as instituteOfOilAndGasDirector
        hide instituteOfOilAndGasDirector members
        directorsAndDeans <|-- instituteOfOilAndGasDirector

        entity "Директор института рыбного хозяйства, биологии и природопользования" as instituteOfFisheryBiologyAndNaturalResourceManagementDirector
        hide instituteOfFisheryBiologyAndNaturalResourceManagementDirector members
        directorsAndDeans <|-- instituteOfFisheryBiologyAndNaturalResourceManagementDirector

        entity "Директор института градостроительства" as instituteOfUrbanPlanningDirector
        hide instituteOfUrbanPlanningDirector members
        directorsAndDeans <|-- instituteOfUrbanPlanningDirector

        entity "Декан факультета среднего профессионального образования" as facultyOfIntermediateVocationalEducationDean
        hide facultyOfIntermediateVocationalEducationDean members
        directorsAndDeans <|-- facultyOfIntermediateVocationalEducationDean

        entity "Директор института дополнительного профессионального образования" as instituteOfContinuingProfessionalEducationDirector
        hide instituteOfContinuingProfessionalEducationDirector members
        directorsAndDeans <|-- instituteOfContinuingProfessionalEducationDirector

    entity "Заведующие кафедрами" as chairpersons
    hide chairpersons members
    academicCouncil <|-- chairpersons

    entity "Первый отдел" as firstDepartment {
        + Начальник
    }
    rector <-- firstDepartment
'    management <|-- firstDepartment

    ' todo куда относится?
    entity "Президент" as president
    hide president members
    management <|-- president



entity "Бухгалтерия" as accounting {
    + Главный бухгалтер
}
university -- accounting

entity "Отдел кадров" as hrDepartment {
    + Начальник
}
'university <|-- hrDepartment
viceRectorForOrganizationalAndLegalAffairs <-- hrDepartment

entity "Юридический отдел" as legalDepartment {
    + Начальник
}
'university -- legalDepartment
viceRectorForOrganizationalAndLegalAffairs <-- legalDepartment

entity "Студенческая канцелярия" as studentAffairsOffice {
    + Начальник
}
' todo кому подчиняется?
'university -- studentAffairsOffice
viceRectorForOrganizationalAndLegalAffairs <-- studentAffairsOffice

entity "Общий отдел" as generalDepartment {
    + Начальник
}
'university -- generalDepartment
viceRectorForOrganizationalAndLegalAffairs <-- generalDepartment
    entity "Отдел делопроизводства" as documentManagementDepartment
    generalDepartment <|-- documentManagementDepartment
    entity "Секретариат руководства" as executiveSecretariat
    generalDepartment <|-- executiveSecretariat
    entity "Военно-учетный стол" as militaryRegistrationDesk
    generalDepartment <|-- militaryRegistrationDesk
    entity "Архив" as archive
    generalDepartment <|-- archive

entity "Международный отдел" as internationalRelationsOffice {
    + Начальник
}
' todo кому подчиняется?
'university -- internationalRelationsOffice
viceRectorForAdmissionsAndInternationalActivities <-- internationalRelationsOffice

entity "Отдел академической мобильности" as academicMobilityOffice {
    + Начальник
}
'university -- academicMobilityOffice
viceRectorForAdmissionsAndInternationalActivities <-- academicMobilityOffice

entity "Управление массовых коммуникаций и медиа-проектов" as massCommunicationsAndMediaProjectsManagement {
    + Начальник
}
'university -- massCommunicationsAndMediaProjectsManagement
viceRectorForEducationalWorkAndPublicRelations <-- massCommunicationsAndMediaProjectsManagement
    entity "Пресс-центр АГТУ" as AGTUPressCenter {
        + Директор
    }
    massCommunicationsAndMediaProjectsManagement <|-- AGTUPressCenter
    entity "Отдел медиа-проектов" as mediaProjectsDepartment {
        + Начальник
    }
    massCommunicationsAndMediaProjectsManagement <|-- mediaProjectsDepartment
    entity "Рекламно-информационный центр" as advertisingAndInformationCenter {
        + Директор
    }
    massCommunicationsAndMediaProjectsManagement <|-- advertisingAndInformationCenter

entity "Управление по организационно-воспитательной работе" as organizationalAndEducationalWorkManagement {
    + Начальник
}
'university -- organizationalAndEducationalWorkManagement
viceRectorForEducationalWorkAndPublicRelations <-- organizationalAndEducationalWorkManagement
    entity "Отдел по культурно-массовой работе" as culturalAndMassWorkDepartment {
        + Начальник
    }
    organizationalAndEducationalWorkManagement <|-- culturalAndMassWorkDepartment
    entity "Отдел по воспитательной и социальной работе" as educationalAndSocialWorkDepartment {
        + Начальник
    }
    university <|-- educationalAndSocialWorkDepartment
    entity "Спортивный клуб" as sportsClub {
        + Начальник
    }
    educationalAndSocialWorkDepartment <|-- sportsClub
    entity "Центр социально-психологической помощи «Доверие»" as TrustSocialAndPsychologicalSupportCenter {
        + Директор
    }
    educationalAndSocialWorkDepartment <|-- TrustSocialAndPsychologicalSupportCenter
    entity "Музей истории АГТУ" as AGTUHistoryMuseum {
        + Директор
    }
    educationalAndSocialWorkDepartment <|-- AGTUHistoryMuseum
    entity "Студенческий совет АГТУ" as AGTUStudentCouncil {
        + Председатель
    }
    educationalAndSocialWorkDepartment <|-- AGTUStudentCouncil
        entity "Студенческий совет института экономики и права" as instituteOfEconomicsAndLawStudentCouncil {
            + Председатель
        }
        AGTUStudentCouncil <|-- instituteOfEconomicsAndLawStudentCouncil
        entity "Студенческий совет института информационных технологий и коммуникаций" as instituteOfInformationTechnologiesAndCommunicationsStudentCouncil {
            + Председатель
        }
        AGTUStudentCouncil <|-- instituteOfInformationTechnologiesAndCommunicationsStudentCouncil
        entity "Студенческий совет института морских технологий, энергетики и транспорта" as instituteOfMarineTechnologiesEnergyAndTransportStudentCouncil {
            + Председатель
        }
        AGTUStudentCouncil <|-- instituteOfMarineTechnologiesEnergyAndTransportStudentCouncil
        entity "Студенческий совет института нефти и газа" as instituteOfOilAndGasStudentCouncil {
            + Председатель
        }
        AGTUStudentCouncil <|-- instituteOfOilAndGasStudentCouncil
        entity "Студенческий совет института рыбного хозяйства, биологии и природопользования" as instituteOfFisheryBiologyAndNaturalResourceManagementStudentCouncil {
            + Председатель
        }
        AGTUStudentCouncil <|-- instituteOfFisheryBiologyAndNaturalResourceManagementStudentCouncil
        entity "Студенческий совет института градостроительства" as instituteOfUrbanPlanningStudentCouncil {
            + Председатель
        }
        AGTUStudentCouncil <|-- instituteOfUrbanPlanningStudentCouncil
        entity "Студенческий совет факультета среднего профессионального образования" as facultyOfIntermediateVocationalEducationStudentCouncil {
            + Председатель
        }
        AGTUStudentCouncil <|-- facultyOfIntermediateVocationalEducationStudentCouncil
        ' todo следующий студсовет существует?
        entity "Студенческий совет института дополнительного профессионального образования" as facultyOfIntermediateVocationalEducationStudentCouncilStudentCouncil {
            + Председатель
        }
        AGTUStudentCouncil <|-- facultyOfIntermediateVocationalEducationStudentCouncilStudentCouncil

    ' todo кому подчиняется?
    entity "Профстудком АГТУ" as AGTUStudentTradeUnionCommittee {

    }
    educationalAndSocialWorkDepartment <|-- AGTUStudentTradeUnionCommittee

entity "Физкультурно-спортивное сооружение 'Спорткомплекс'" as sportsFacility {
    + Директор
}
'university -- sportsFacility
viceRectorForEducationalWorkAndPublicRelations <-- sportsFacility

entity "Управление информационных систем и технологий" as informationSystemsAndTechnologiesManagement {
    + Начальник
}
'university -- informationSystemsAndTechnologiesManagement
viceRectorForInfrastructureDevelopmentAndInformatization <-- informationSystemsAndTechnologiesManagement
    entity "Отдел АСУ" as automationSystemsDepartment {
        + Начальник
    }
    informationSystemsAndTechnologiesManagement <|-- automationSystemsDepartment
    entity "Отдел информационной безопасности" as informationSecurityDepartment {
        + Начальник
    }
    informationSystemsAndTechnologiesManagement <|-- informationSecurityDepartment
    entity "Сервисный отдел" as serviceDepartment {
        + Начальник
    }
    informationSystemsAndTechnologiesManagement <|-- serviceDepartment
    entity "Отдел вычислительных сетей и связи" as computerNetworksAndCommunicationsDepartment {
        + Начальник
    }
    informationSystemsAndTechnologiesManagement <|-- computerNetworksAndCommunicationsDepartment

entity "Диспетчерский отдел" as dispatchDepartment {
    + Начальник
}
'university -- dispatchDepartment
viceRectorForInfrastructureDevelopmentAndInformatization <-- dispatchDepartment

entity "Учебный отдел" as academicDepartment {
    + Начальник
}
'university -- academicDepartment
viceRectorForAcademicAffairs <-- academicDepartment

entity "Центр содействия трудоустройству выпускников АГТУ" as careerDevelopmentCenter {
    + Директор
}
'university -- careerDevelopmentCenter
viceRectorForAcademicAffairs <-- careerDevelopmentCenter

entity "Отдел методического обеспечения учебного процесса" as educationalProcessSupportDepartment {
    + Начальник
}
'university -- educationalProcessSupportDepartment
viceRectorForAcademicAffairs <-- educationalProcessSupportDepartment

entity "Центр образовательной политики" as educationalPolicyCenter {
    + Директор
}
'university -- educationalPolicyCenter
viceRectorForAcademicAffairs <-- educationalPolicyCenter

entity "Издательство АГТУ" as AGTUPublishingHouse {
    + Директор
}
'university -- AGTUPublishingHouse
viceRectorForAdmissionsAndInternationalActivities <-- AGTUPublishingHouse
    entity "Отдел допечатной подготовки изданий" as prepressDepartment {
        + Начальник
    }
    AGTUPublishingHouse <|-- prepressDepartment

entity "Научно-образовательный центр профессиональных компетенций" as professionalCompetenciesCenter {
     + Директор
}
'university -- professionalCompetenciesCenter
viceRectorForAcademicAffairs <-- professionalCompetenciesCenter

entity "Центр довузовской подготовки, профориентации и приему в вуз" as preuniversityPreparationAndAdmissionCenter {
    + Директор
}
'university -- preuniversityPreparationAndAdmissionCenter
viceRectorForAdmissionsAndInternationalActivities <-- preuniversityPreparationAndAdmissionCenter

entity "Научная библиотека" as scientificLibrary {
    + Директор
}
'university -- scientificLibrary
viceRectorForAdmissionsAndInternationalActivities <-- scientificLibrary
    entity "Отдел комплектования" as acquisitionDepartment {
        + Начальник
    }
    scientificLibrary <|-- acquisitionDepartment
    entity "Отдел каталогизации" as catalogingDepartment {
        + Начальник
    }
    scientificLibrary <|-- catalogingDepartment
    entity "Информационно-библиографический отдел" as informationAndBibliographyDepartment {
        + Начальник
    }
    scientificLibrary <|-- informationAndBibliographyDepartment
    entity "Отделы обслуживания" as serviceDepartments {
        + Начальник
    }
    scientificLibrary <|-- serviceDepartments
    entity "Читальный зал электронных ресурсов" as electronicResourcesReadingRoom {
        ' todo кто руководитель?
    }
    hide electronicResourcesReadingRoom members
    scientificLibrary <|-- electronicResourcesReadingRoom
    ' todo следующие отделы нужны?
'    entity "Отдел научной литературы" as scientificLiteratureDepartment {
'
'    }
'    scientificLibrary -- scientificLiteratureDepartment
'    entity "Студенческий читальный зал" as studentReadingRoom {
'
'    }
'    scientificLibrary -- studentReadingRoom
'    entity "Отдел учебной литературы" as educationalLiteratureDepartment {
'
'    }
'    scientificLibrary -- educationalLiteratureDepartment
'    entity "Читальный зал экономической и юридической литературы" as economicsAndLawReadingRoom {
'
'    }
'    scientificLibrary -- economicsAndLawReadingRoom
'    entity "Читальный зал периодических изданий" as periodicalsReadingRoom {
'
'    }
'    scientificLibrary -- periodicalsReadingRoom

entity "Центр научно-инновационного развития" as scientificAndInnovativeDevelopmentCenter {
    + Директор
}
'university -- scientificAndInnovativeDevelopmentCenter
viceRectorForResearchAndInnovations <-- scientificAndInnovativeDevelopmentCenter

entity "Отдел научных проектов" as researchProjectsDepartment {
    + Начальник
}
' todo кому подчиняется?
'scientificAndInnovativeDevelopmentCenter -- researchProjectsDepartment
viceRectorForResearchAndInnovations <-- researchProjectsDepartment

entity "Научно-исследовательская часть" as researchDivision {
    + Начальник
}
'university -- researchDivision
viceRectorForResearchAndInnovations <-- researchDivision

entity "Отдел подготовки кадров высшей квалификации" as postgraduateTrainingDepartment {
    + Начальник
}
'university -- postgraduateTrainingDepartment
viceRectorForResearchAndInnovations <-- postgraduateTrainingDepartment

entity "Редакция журнала «Вестник АГТУ»" as AGTUJournalEditorialOffice {
    + Заведующий
}
' todo кому подчиняется?
university <-- AGTUJournalEditorialOffice

entity "Редакция научных журналов" as scientificJournalsEditorialOffice {
    + Начальник
}
' todo кому подчиняется?
university <-- scientificJournalsEditorialOffice

entity "Отдел маркетинга" as marketingDepartment {
    + Начальник
}
'university -- marketingDepartment
viceRectorForFinancialAndEconomicAffairs <-- marketingDepartment

entity "Договорный отдел" as contractDepartment {
    + Начальник
}
'university -- contractDepartment
viceRectorForFinancialAndEconomicAffairs <-- contractDepartment

entity "Отдел материально-технического снабжения" as materialsAndTechnicalSupplyDepartment {
    + Начальник
}
'university -- materialsAndTechnicalSupplyDepartment
viceRectorForFinancialAndEconomicAffairs <-- materialsAndTechnicalSupplyDepartment
    ' todo где взять положение?
    entity "Склад" as warehouse {
        + Начальник
    }
    materialsAndTechnicalSupplyDepartment <|-- warehouse

entity "Планово-экономический отдел" as planningAndEconomicDepartment {
    + Начальник
}
'university -- planningAndEconomicDepartment
viceRectorForFinancialAndEconomicAffairs <-- planningAndEconomicDepartment
    entity "Сектор бюджетирования, аналитического учёта и контроля" as budgetingAndAnalyticalControlSector {
        + Начальник
    }
    planningAndEconomicDepartment <|-- budgetingAndAnalyticalControlSector
    entity "Сектор труда и заработной платы" as laborAndWageSector {
        + Начальник
    }
    planningAndEconomicDepartment <|-- laborAndWageSector


entity "Отдел внебюджетной деятельности и социальной защиты" as extrabudgetaryActivitiesAndSocialProtectionDepartment {
    + Начальник
}
'university -- extrabudgetaryActivitiesAndSocialProtectionDepartment
viceRectorForFinancialAndEconomicAffairs <-- extrabudgetaryActivitiesAndSocialProtectionDepartment

entity "Административно-хозяйственное управление" as administrativeAndEconomicManagement {
    + Начальник
}
'university -- administrativeAndEconomicManagement
viceRectorForInfrastructureDevelopmentAndInformatization <-- administrativeAndEconomicManagement
    entity "Отдел по комплексному обслуживанию вуза" as comprehensiveUniversityServiceDepartment {
        + Начальник
    }
    administrativeAndEconomicManagement <|-- comprehensiveUniversityServiceDepartment
    entity "Хозяйственный отдел" as economicDepartment {
        + Начальник
    }
    administrativeAndEconomicManagement <|-- economicDepartment
    entity "Транспортный отдел" as transportDepartment {
        + Начальник
    }
    administrativeAndEconomicManagement <|-- transportDepartment

entity "Отдел по управлению имуществом и проектами" as propertyAndProjectManagementDepartment {
    + Начальник
}
'university -- propertyAndProjectManagementDepartment
viceRectorForInfrastructureDevelopmentAndInformatization <-- propertyAndProjectManagementDepartment

entity "Отдел охраны труда и техники безопасности" as laborProtectionAndTechnicalSafetyDepartment {
    + Начальник
}
'university -- laborProtectionAndTechnicalSafetyDepartment
viceRectorForInfrastructureDevelopmentAndInformatization <-- laborProtectionAndTechnicalSafetyDepartment

' todo нужны?
'entity "Общежития" as dormitories {
'
'}
'university -- dormitories
'    entity "Вахта общежития №4" as dormitoryGuardhouse4 {
'
'    }
'    dormitories -- dormitoryGuardhouse4
'    entity "Вахта общежития №8" as dormitoryGuardhouse8 {
'
'    }
'    dormitories -- dormitoryGuardhouse8
'    entity "Вахта общежития №10" as dormitoryGuardhouse10 {
'
'    }
'    dormitories -- dormitoryGuardhouse10

' todo нужны?
'entity "Вахты учебных корпусов" as academicBuildingsGuardhouses {
'
'}
'university -- academicBuildingsGuardhouses
'    entity "Главный учебный корпус" as mainAcademicBuildingGuardhouse {
'
'    }
'    academicBuildingsGuardhouses -- mainAcademicBuildingGuardhouse
'    entity "Учебный корпус №2" as academicBuilding2Guardhouse {
'
'    }
'    academicBuildingsGuardhouses -- academicBuilding2Guardhouse
'    entity "Учебный корпус №3" as academicBuilding3Guardhouse {
'
'    }
'    academicBuildingsGuardhouses -- academicBuilding3Guardhouse
'    entity "Учебный корпус №4" as academicBuilding4Guardhouse {
'
'    }
'    academicBuildingsGuardhouses -- academicBuilding4Guardhouse
'    entity "Учебный корпус №5" as academicBuilding5Guardhouse {
'
'    }
'    academicBuildingsGuardhouses -- academicBuilding5Guardhouse
'    entity "Учебный корпус №6" as academicBuilding6Guardhouse {
'
'    }
'    academicBuildingsGuardhouses -- academicBuilding6Guardhouse
'    entity "Учебный корпус №7" as academicBuilding7Guardhouse {
'
'    }
'    academicBuildingsGuardhouses -- academicBuilding7Guardhouse
'    entity "Учебный корпус №8" as academicBuilding8Guardhouse {
'
'    }
'    academicBuildingsGuardhouses -- academicBuilding8Guardhouse
'    entity "Учебный корпус №9" as academicBuilding9Guardhouse {
'
'    }
'    academicBuildingsGuardhouses -- academicBuilding9Guardhouse
'    entity "Учебный корпус №10-11" as academicBuilding10_11Guardhouse {
'
'    }
'    academicBuildingsGuardhouses -- academicBuilding10_11Guardhouse

' todo нужны?
'entity "Дополнительные структуры" as additionalStructures {
'
'}
'university -- additionalStructures
'    entity "Медицинский пункт" as medicalPoint {
'
'    }
'    additionalStructures -- medicalPoint
'    entity "Профсоюзный комитет сотрудников ФГБОУ ВО 'АГТУ'" as AGTUStaffTradeUnionCommittee {
'
'    }
'    additionalStructures -- AGTUStaffTradeUnionCommittee

' todo нужны?
'entity "Контрольно-пропускные пункты" as checkpoints {
'
'}
'university -- checkpoints
'    entity "КПП со стороны ул. Татищева" as checkpointTatischevaStreet {
'
'    }
'    checkpoints -- checkpointTatischevaStreet
'    entity "КПП со стороны ул. 28 Армии" as checkpoint28ArmyStreet {
'
'    }
'    checkpoints -- checkpoint28ArmyStreet





@enduml
