/*
 * API Шлюз. Категории объявлений
 *
 * API Шлюза для управления категориями объявлений
 *
 * The version of the OpenAPI document: 0.0.4
 *
 * Generated by: https://openapi-generator.tech
 */

using System.ComponentModel;
using System.Runtime.Serialization;
using BulletInBoardServer.Controllers.CategoriesController.Converters;
using Newtonsoft.Json;

namespace BulletInBoardServer.Controllers.CategoriesController.Models
{ 
        /// <summary>
        /// Ответы:   announcementCategoryDeletionForbidden - Пользователь не имеет права удалить категорию объявлений   announcementCategoryDoesNotExist - Категория объявлений с указанным id не существует 
        /// </summary>
        /// <value>Ответы:   announcementCategoryDeletionForbidden - Пользователь не имеет права удалить категорию объявлений   announcementCategoryDoesNotExist - Категория объявлений с указанным id не существует </value>
        [TypeConverter(typeof(CustomEnumConverter<DeleteAnnouncementCategoryResponses>))]
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum DeleteAnnouncementCategoryResponses
        {
            
            /// <summary>
            /// Enum AnnouncementCategoryDeletionForbidden for announcementCategoryDeletionForbidden
            /// </summary>
            [EnumMember(Value = "announcementCategoryDeletionForbidden")]
            AnnouncementCategoryDeletionForbidden = 1,
            
            /// <summary>
            /// Enum AnnouncementCategoryDoesNotExist for announcementCategoryDoesNotExist
            /// </summary>
            [EnumMember(Value = "announcementCategoryDoesNotExist")]
            AnnouncementCategoryDoesNotExist = 2
        }
}
