/*
 * API Шлюз. Категории объявлений
 *
 * API Шлюза для управления категориями объявлений
 *
 * The version of the OpenAPI document: 0.0.4
 *
 * Generated by: https://openapi-generator.tech
 */

using System.ComponentModel;
using System.Runtime.Serialization;
using BulletInBoardServer.Controllers.CategoriesController.Converters;
using Newtonsoft.Json;

namespace BulletInBoardServer.Controllers.CategoriesController.Models
{ 
        /// <summary>
        /// Ответы:   nameIsNullOrEmpty - Название категории объявлений null, пустое или состоит только из пробельных символов   colorIsInvalidHex - Код цвета передан не в HEX формате    announcementCategoryUpdatingForbidden - Пользователь не имеет права редактировать категорию объявлений   announcementCategoryDoesNotExist - Категория объявлений с указанным id не существует   
        /// </summary>
        /// <value>Ответы:   nameIsNullOrEmpty - Название категории объявлений null, пустое или состоит только из пробельных символов   colorIsInvalidHex - Код цвета передан не в HEX формате    announcementCategoryUpdatingForbidden - Пользователь не имеет права редактировать категорию объявлений   announcementCategoryDoesNotExist - Категория объявлений с указанным id не существует   </value>
        [TypeConverter(typeof(CustomEnumConverter<UpdateAnnouncementCategoryResponses>))]
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum UpdateAnnouncementCategoryResponses
        {
            
            /// <summary>
            /// Enum ColorIsInvalidHex for colorIsInvalidHex
            /// </summary>
            [EnumMember(Value = "colorIsInvalidHex")]
            ColorIsInvalidHex = 1,
            
            /// <summary>
            /// Enum NameIsNullOrEmpty for nameIsNullOrEmpty
            /// </summary>
            [EnumMember(Value = "nameIsNullOrEmpty")]
            NameIsNullOrEmpty = 2,
            
            /// <summary>
            /// Enum AnnouncementCategoryUpdatingForbidden for announcementCategoryUpdatingForbidden
            /// </summary>
            [EnumMember(Value = "announcementCategoryUpdatingForbidden")]
            AnnouncementCategoryUpdatingForbidden = 3,
            
            /// <summary>
            /// Enum AnnouncementCategoryDoesNotExist for announcementCategoryDoesNotExist
            /// </summary>
            [EnumMember(Value = "announcementCategoryDoesNotExist")]
            AnnouncementCategoryDoesNotExist = 4
        }
}
