/*
 * API Шлюз. Категории объявлений
 *
 * API Шлюза для управления категориями объявлений
 *
 * The version of the OpenAPI document: 0.0.2
 *
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;

namespace BulletInBoardServer.Controllers.CategoriesController.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public class UpdateAnnouncementCategoriesSubscriptionsDto : IEquatable<UpdateAnnouncementCategoriesSubscriptionsDto>
    {
        /// <summary>
        /// Gets or Sets ChangedIds
        /// </summary>
        [Required]
        [DataMember(Name="changedIds", EmitDefaultValue=false)]
        public List<Guid> ChangedIds { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class UpdateAnnouncementCategoriesSubscriptionsDto {\n");
            sb.Append("  ChangedIds: ").Append(ChangedIds).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((UpdateAnnouncementCategoriesSubscriptionsDto)obj);
        }

        /// <summary>
        /// Returns true if UpdateAnnouncementCategoriesSubscriptionsDto instances are equal
        /// </summary>
        /// <param name="other">Instance of UpdateAnnouncementCategoriesSubscriptionsDto to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(UpdateAnnouncementCategoriesSubscriptionsDto other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    ChangedIds == other.ChangedIds ||
                    ChangedIds != null &&
                    other.ChangedIds != null &&
                    ChangedIds.SequenceEqual(other.ChangedIds)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (ChangedIds != null)
                    hashCode = hashCode * 59 + ChangedIds.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(UpdateAnnouncementCategoriesSubscriptionsDto left, UpdateAnnouncementCategoriesSubscriptionsDto right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(UpdateAnnouncementCategoriesSubscriptionsDto left, UpdateAnnouncementCategoriesSubscriptionsDto right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
