@startuml
'https://plantuml.com/class-diagram

hide members

class main
class group_1
class group_2
class group_3
class group_4
class group_5
class group_6
class group_7

main --> group_1

group_1 --> group_2
group_1 --> group_3

group_2 --> group_4

group_3 --> group_4
group_3 --> group_5

group_4 --> group_6

group_5 --> group_7

@enduml