@startuml
'https://plantuml.com/class-diagram

hide members

class usergroup_1
class usergroup_2
class usergroup_3
class usergroup_4
class usergroup_5
class usergroup_6
class usergroup_7

usergroup_1 --> usergroup_3
usergroup_2 --> usergroup_3
usergroup_4 --> usergroup_2
usergroup_5 --> usergroup_7

@enduml