openapi: 3.0.3
info:
  title: Схемы enum ответов API шлюза категорий объявлений
  description: Схемы enum ответов API шлюза категорий объявлений
  version: 0.0.1
servers:
  - url: 'https://localhost:8080'
paths:
  
components: 
  schemas:
    createAnnouncementCategoryResponses:
      type: string
      enum:
        # 201
        - created
        # 400
        - colorIsIncorrectHex
        # 401
        - unauthorized
        # 403
        - announcementCategoryCreationForbidden
      description: >
        Ответы:
          created - Категория объявлений создана
          colorIsIncorrectHex - Код цвета передан не в HEX формате 
          unauthorized - Пользователь не авторизован для выполнения операции
          announcementCategoryCreationForbidden - Пользователь не имеет права создать категорию объявлений

    getAllAnnouncementCategoriesResponses:
      type: string
      enum:
        # 200
        - ok
        # 401
        - unauthorized
        # 403
        - announcementCategoryListAccessForbidden
      description: >
        Ответы:
          ok - Ок
          unauthorized - Пользователь не авторизован для выполнения операции
          announcementCategoryListAccessForbidden - Пользователь не имеет права получить список категорий объявлений
        
    updateAnnouncementCategoryResponses:
      type: string
      enum:
        # 200
        - ok
        # 400
        - incorrectIdentifierFormat
        # 401
        - unauthorized
        # 403
        - announcementCategoryUpdatingForbidden
        # 404
        - announcementCategoryDoesNotExist
      description: >
        Ответы:
          ok - Ок
          incorrectIdentifierFormat - Некорректный формат идентификатора
          unauthorized - Пользователь не авторизован для выполнения операции
          announcementCategoryUpdatingForbidden - Пользователь не имеет права редактировать категорию объявлений
          announcementCategoryDoesNotExist - Категория объявлений с указанным id не существует  

    deleteAnnouncementCategoryResponses:
      type: string
      enum:
        # 200
        - ok
        # 400
        - incorrectIdentifierFormat
        # 401
        - unauthorized
        # 403
        - announcementCategoryDeletionForbidden
        # 404
        - announcementCategoryDoesNotExist
      description: >
        Ответы:
          ok - Ок
          incorrectIdentifierFormat - Некорректный формат идентификатора
          unauthorized - Пользователь не авторизован для выполнения операции
          announcementCategoryDeletionForbidden - Пользователь не имеет права удалить категорию объявлений
          announcementCategoryDoesNotExist - Категория объявлений с указанным id не существует
        
    getAnnouncementCategoriesSubscriptionsResponses:
      type: string
      enum:
        # 200
        - ok
        # 401
        - unauthorized
        # 403
        - getSubscriptionsListForbidden
      description: >
        Ответы:
          ok - Ок
          unauthorized - Пользователь не авторизован для выполнения операции
          getSubscriptionsListForbidden - Пользователь не имеет права получить список категорий объявлений, на которые подписан
        
    updateAnnouncementCategoriesSubscriptionsResponses:
      type: string
      enum:
        # 200
        - ok
        # 400
        - incorrectIdentifierFormat
        # 401
        - unauthorized
        # 403
        - updateSubscriptionsForbidden
        # 404
        - categoriesDoNotExist
      description: >
        Ответы:
          ok - Ок
          incorrectIdentifierFormat - Некорректный формат идентификатора
          unauthorized - Пользователь не авторизован для выполнения операции
          updateSubscriptionsForbidden - Пользователь не имеет права получить список категорий объявлений, на которые подписан
          categoriesDoNotExist - В качестве одного или нескольких id категорий объявлений прикреплен несуществующий в базе id