openapi: 3.0.3
info:
  title: Схемы enum ответов API шлюза групп пользователей
  description: Схемы enum ответов API шлюза групп пользователей
  version: 0.0.1
servers:
  - url: 'https://localhost:8080'
paths:
  
components: 
  schemas:
    createUsergroupResponses:
      type: string
      enum:
        # 201
        - created
        # 400
        - nameNullOrWhitespace
        # 401
        - unauthorized
        # 403
        - usergroupCreationForbidden
        # 404
        - usersDoNotExist
        - usergroupsDoNotExist
        # 409
        - adminCannotBeOrdinaryMember
        - cyclicDependency
      description: >
        Ответы:
          created - Группа пользователей создана
          nameNullOrWhitespace - Название группы пользователей null или состоит исключительно из пробельных символов
          unauthorized - Пользователь не авторизован для выполнения операции
          usergroupCreationForbidden - Пользователь не имеет права создать группу пользователей
          usersDoNotExist - В качестве одного или нескольких id пользователей прикреплен несуществующий в базе id
          usergroupsDoNotExist - В качестве одного или нескольких id групп пользователей прикреплен несуществующий в базе id
          adminCannotBeOrdinaryMember - Идентификатор администратора передан в массиве идентификаторов участников
          cyclicDependency - Группа пользователей не может быть создана, так как порождает цикл на графе групп пользователей

    getAllUsergroupsResponses:
      type: string
      enum:
        # 200
        - ok
        # 401
        - unauthorized
        # 403
        - getAllUsergroupsForbidden
    
    getUsergroupDetailsResponses:
      type: string
      enum:
        # 200
        - ok
        # 400
        - incorrectIdentifierFormat
        # 401
        - unauthorized
        # 403
        - getUsergroupDetailsForbidden
        # 404
        - usergroupDoesNotExist
      description: >
        Ответы:
          ok - Ок
          incorrectIdentifierFormat - Некорректный формат идентификатора 
          unauthorized - Пользователь не авторизован для выполнения операции
          getUsergroupDetailsForbidden - Пользователь не имеет права запрашивать детали группы пользователей
        
    updateUsergroupResponses:
      type: string
      enum:
        # 200
        - ok
        # 400
        - incorrectIdentifierFormat
        - nameIsEmptyOrWhitespace
        # 401
        - unauthorized
        # 403
        - updateUsergroupForbidden
        # 404
        - usersDoNotExist
        # 409
        - adminCannotBeOrdinaryMember
      description: >
        Ответы:
          ok - Ок
          incorrectIdentifierFormat - Некорректный формат идентификатора
          nameIsEmptyOrWhitespace - Имя не содержит символов или содержит исключительно пробельные
          unauthorized - Пользователь не авторизован для выполнения операции 
          updateUsergroupForbidden - Пользователь не имеет права редактировать группу пользователей
          usersDoNotExist - В качестве одного или нескольких id пользователей прикреплен несуществующий в базе id
          adminCannotBeOrdinaryMember - Идентификатор администратора передан в массиве идентификаторов участников

    deleteUsergroupResponses:
      type: string
      enum:
        # 200
        - ok
        # 400
        - incorrectIdentifierFormat
        # 401
        - unauthorized
        # 403
        - usergroupDeletionForbidden
        # 404
        - usergroupDoesNotExist
      description: >
        Ответы:
          ok - Ок
          incorrectIdentifierFormat - Некорректный формат идентификатора
          unauthorized - Пользователь не авторизован для выполнения операции 
          usergroupDeletionForbidden - Пользователь не имеет права удалить группу пользователей
          usergroupDoesNotExist - В качестве id группы пользователей прикреплен несуществующий в базе id
  