@startuml
'https://plantuml.com/use-case-diagram

left to right direction

:Сотрудник: as employee

rectangle "Доска объявлений" {
    employee --> (Создать объявление)
     
    (Создать объявление) --> (Указать текст объявления) : include
    (Создать объявление) --> (Выбрать получателей) : include
    (Создать объявление) <.. (Прикрепить файлы) : extend
    (Создать объявление) <.. (Прикрепить опрос) : extend
    (Создать объявление) <.. (Установить срок автоматического сокрытия) : extend
    (Создать объявление) <.. (Задать режим отложенной публикации) : extend
    
    (Прикрепить файлы) --> (Загрузить файлы) : include
    (Прикрепить опрос) --> (Создать опрос) : include
    
    (Задать режим отложенной публикации) --> (Задать дату и время публикации) : include
}
@enduml