@startuml
'https://plantuml.com/use-case-diagram

left to right direction

:Сотрудник: as employee

rectangle "Доска объявлений" {
    employee --> (Создать опрос)
    (Создать опрос) --> (Указать вопросы) : include
    (Создать опрос) --> (Задать варианты ответов) : include
    (Создать опрос) <.. (Задать анонимность голосования) : extend
    (Создать опрос) <.. (Задать возможность выбора нескольких вариантов ответов) : extend
    (Создать опрос) <.. (Задать ограничение времени голосования) : extend 
    
    (Задать ограничение времени голосования) --> (Уазать продолжительность голосования) : include
}

@enduml