@startuml
'https://plantuml.com/use-case-diagram

left to right direction

:Сотрудник: as employee

rectangle "Доска объявлений" {
    employee --> (Редактировать объявление)
     
    (Редактировать объявление) <.. (Изменить текст объявления) : extend
    (Редактировать объявление) <.. (Изменить группы получателей) : extend
    (Редактировать объявление) <.. (Задать срок автоматического сокрытия) : extend
    (Редактировать объявление) <.. (Изменить срок автоматического сокрытия) : extend
    (Редактировать объявление) <.. (Отменить автоматическое сокрытие) : extend
    (Редактировать объявление) <.. (Изменить дату и время отложенной публикации) : extend
    (Редактировать объявление) <.. (Прикрепить новые файлы) : extend
    (Редактировать объявление) <.. (Удалить прикрепленные файлы) : extend
    (Редактировать объявление) <.. (Прикрепить опрос) : extend
    
'    note "Если он не был прикреплен ранее" as N1
'    (Прикрепить опрос) .right. N1
}
@enduml