@startuml
'https://plantuml.com/use-case-diagram 

left to right direction

:Студент: as student
:Сотрудник: as employee
:Администратор группы: as groupAdmin
:Администратор: as admin

rectangle "Доска объявлений" {
    student --> (Просмотреть доску объявлений)
    student --> (Получить уведомление о новом объявлении)
    
    (Просмотреть доску объявлений) <|-- (Скачать файлы)
    (Просмотреть доску объявлений) <|-- (Пройти опросы)
    
    (Пройти опросы) <.. (Отменить голос) : extend


    
    student <|-r- employee
    employee --> (Управление объявлениями)
    employee --> (Управление опросами)
    
    
    employee <|-r- groupAdmin
    groupAdmin --> (Добавить пользователя в свою группу)
    groupAdmin --> (Удалить пользователя из своей группы)
    groupAdmin --> (Редактировать права сотрудника в своей группе)
    
    
    
    employee <|-r- admin
    admin --> (Управление сотрудниками)
    admin --> (Управление администраторами групп) 
}



@enduml