@startuml
'https://plantuml.com/use-case-diagram 

left to right direction

:Студент: as student
:Сотрудник: as employee
:Администратор группы: as groupAdmin
:Администратор: as admin

rectangle "Доска объявлений" {
    student --> (<font color="gray">S-2.</font> Получить уведомление о новом объявлении)
    student --> (<font color="gray">S-1.</font> Просмотреть доску объявлений)
    
    student <|-r- employee
    employee --> (<font color="gray">E-2.</font> Управление опросами)
    employee --> (<font color="gray">E-1.</font> Управление объявлениями)
    
    employee <|-r- groupAdmin
    groupAdmin --> (<font color="gray">G-1.</font> Управление своими группами)
    
    employee <|-r- admin
    admin --> (<font color="gray">A-2.</font> Управление администраторами групп) 
    admin --> (<font color="gray">A-1.</font> Управление сотрудниками)
}



@enduml