@startuml
'https://plantuml.com/use-case-diagram

left to right direction

:Администратор: as admin

rectangle "Доска объявлений" {
    (<font color="gray">A-1.</font> Управление сотрудниками) as manage_employees

    admin --> manage_employees
    manage_employees <|-- (<font color="gray">A-1.3.</font> Редактировать права сотрудника в любой группе)
    manage_employees <|-- (<font color="gray">A-1.2.</font> Удалить сотрудника из группы) 
    manage_employees <|-- (<font color="gray">A-1.1.</font> Добавить сотрудника в группу) 
}

@enduml