@startuml
'https://plantuml.com/use-case-diagram

left to right direction

:Сотрудник: as employee

employee --> (Управление опросами)    
(Управление опросами) <|-- (Закрыть опрос) 
(Управление опросами) <|-- (Собрать статистику опроса) 

(Собрать статистику опроса) <.. (Выгрузить результаты опроса) : extend

@enduml