@startuml
'https://plantuml.com/use-case-diagram

left to right direction

:Сотрудник: as employee

employee --> (Управление объявлениями)

(Управление объявлениями) <|-- (Создать объявление) 
(Управление объявлениями) <|-- (Редактировать объявление) 
(Управление объявлениями) <|-- (Скрыть объявление) 
(Управление объявлениями) <|-- (Собрать статистику просмотра объявлений)
(Управление объявлениями) <|-- (Управление скрытыми объявлениями) 
(Управление объявлениями) <|-- (Удалить объявление) 
(Управление объявлениями) <|-- (Сразу опубликовать скрытое объявление) 

(Управление скрытыми объявлениями) <|-- (Просмотреть список скрытых объявлений)
(Управление скрытыми объявлениями) <|-- (Восстановить скрытое объявление)

@enduml