@startuml
'https://plantuml.com/use-case-diagram

left to right direction

admin --> (Управление сотрудниками)

(Управление сотрудниками) <|-- (Добавить сотрудника в группу) 
(Управление сотрудниками) <|-- (Удалить сотрудника из группы) 
(Управление сотрудниками) <|-- (Редактировать права сотрудника в любой группе)

@enduml