@startuml
'https://plantuml.com/use-case-diagram

left to right direction

:Администратор: as admin

admin -- (Управление администраторами групп)
(Управление администраторами групп) <|-- (Назначить администратора группы) 
(Управление администраторами групп) <|-- (Удалить администратора группы)

@enduml