services:
    bulletin_board_service:
        container_name: astu_bulletin_board_service
        hostname: bulletin-board-service
        image: astu/bulletin_board:v1.5
        build:
            context: ../../src
            dockerfile: ./BulletInBoardServer/BulletInBoardServer/Dockerfile
    
    postgres:
        container_name: pg_bulletin_board
        image: postgres:latest
        environment:
            POSTGRES_DB: "bulletin_board"
            POSTGRES_USER: "admin"
            POSTGRES_PASSWORD: "P@$$w0rd"
        ports:
            - "55432:5432"
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U admin -d bulletin_board"]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 10s
        restart: unless-stopped
#        deploy:
#            resources:
#                limits:
#                    cpus: '6'
#                    memory: 2048M
        volumes:
            - ./initdb:/docker-entrypoint-initdb.d
            - ./infrastructure/:/var/lib/postgresql/data
        networks:
            - bulletin_board_network
    
#    auth:
#        container_name: auth_service
#        restart: always
#        build: .
#        image: astu/auth:v1
#        environment:
#            AUTH_DB_CONNECTION: jdbc:postgresql://authDB/authDB
#            AUTH_DB_USER: admin
#            AUTH_DB_PASSWORD: admin
#        env_file:
#            - .env
#        ports:
#            - "50000:50000"
#            - "50001:50001"
#        depends_on:
#            MyDB:
#                condition: service_healthy

networks:
    bulletin_board_network:
        driver: bridge
