version: "3.9"

services:
    postgres:
        container_name: pg_bulletin_board
        image: postgres:latest
        environment:
            POSTGRES_DB: "bulletin_board"
            POSTGRES_USER: "admin"
            POSTGRES_PASSWORD: "P@$$w0rd"
        ports:
            - "55432:5432"
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U admin -d bulletin_board"]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 10s
        restart: unless-stopped
        deploy:
            resources:
                limits:
                    cpus: '2'
                    memory: 2048M
        networks:
            - bulletin_board_network

networks:
    bulletin_board_network:
        driver: bridge
