@startuml
'https://plantuml.com/use-case-diagram

left to right direction

:Администратор: as admin

rectangle "Доска объявлений" {
    (<font color="gray">A-1.</font> Регистрация пользователей) as registerUsers
    (<font color="gray">A-1.2.</font> Зарегистрировать несколько пользователей) as registerSeveralUsers

    admin --> registerUsers
    registerUsers <|-- (<font color="gray">A-1.1.</font> Зарегистрировать одного пользователя)
    registerUsers <|-- registerSeveralUsers 
    registerSeveralUsers <.. (<font color="gray">A-1.3.</font> Выбрать файл с пользователями) : extend
}

@enduml