@startuml
'https://plantuml.com/use-case-diagram

left to right direction

:Администратор: as admin

rectangle "Доска объявлений" {
    (<font color="gray">A-1.</font> Управление всеми группами) as manage_all_usergroups

    admin -- manage_all_usergroups
    manage_all_usergroups <|-- (<font color="gray">A-1.2.</font> Удалить групп пользователей)
    manage_all_usergroups <|-- (<font color="gray">A-1.4.</font> Редактировать группу пользователей)
    manage_all_usergroups <|-- (<font color="gray">A-1.3.</font> Создать группу пользователей)
    manage_all_usergroups <|-- (<font color="gray">A-1.2.</font> Редактировать права сотрудника в группе) 
    manage_all_usergroups <|-- (<font color="gray">A-1.1.</font> Просмотреть список групп пользователей) 
}


@enduml