/*
 * API Шлюз. Пользователи
 *
 * API Шлюз. Пользователи
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

using System;
using BulletInBoardServer.Controllers.UsersController.Attributes;
using BulletInBoardServer.Controllers.UsersController.Models;
using Microsoft.AspNetCore.Mvc;

namespace BulletInBoardServer.Controllers.UsersController.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public abstract class UsersApiController : ControllerBase
    { 
        /// <summary>
        /// Регистрация пользователя
        /// </summary>
        /// <param name="userSummaryDto"></param>
        /// <response code="201">Ok</response>
        /// <response code="400">Bad Request</response>
        /// <response code="409">Conflict</response>
        /// <response code="500">Internal Server Error</response>
        [HttpPost]
        [Route("/api/users/register")]
        [Consumes("application/json")]
        [ValidateModelState]
        [ProducesResponseType(statusCode: 201, type: typeof(Guid))]
        public abstract IActionResult RegisterUser([FromBody]UserSummaryDto userSummaryDto);
    }
}
