@startuml
'https://plantuml.com/class-diagram

'left to right direction

class Announcement {
    + GetId(): Guid
    
    + GetContent(): string
    + SetContent(content: string): void
    
    + GetAuthor(): User
    + SetAuthor(author: User): void
    
    + GetCategories(): AnnouncementCategory[] 
    
    + GetAudience(): UserGroup[]
    
    + GetPublishedAt(): DateTime?
    + SetPublishedAt(moment: DateTime?): void
    + IsPublished(): void
    
    + GetAutoPublishingAt(): DateTime?
    + SetAutoPublishingAt(moment: DateTime?): void
    + ExpectsAutoPublishing(): bool
    
    + GetHiddenAt(): DateTime?
    + SetHiddenAt(moment: DateTime?): void
    + IsHidden(): bool
    
    + GetAutoHidingAt(): DateTime?
    + SetAutoAutoHidingAt(moment: DateTime?): void
    + ExpectsAutoHiding(): bool
    
    + GetAttachments(): IAttachment?
}
hide Announcement fields

class AnnouncementCategory {
    + GetId(): Guid
    + GetName(): string
    + SetName(name: string): void
    
    + GetSubscribers(): User[]
    + Subscribe(user: User): void
    + Unsubscribe(user: User): void
}
hide AnnouncementCategory fields
Announcement "*" o-- "*" AnnouncementCategory

interface IAttachment {
    
}
Announcement "1..*" <-- "*" IAttachment

class File extends IAttachment {
    + GetId(): void
    + GetName(): string    
    + GetHash(): string
    + GetLinksCount(): int
    
    + AddLink(): void
    + RemoveLink(): void
}
hide File fields

class UserGroup {
    + GetId(): Guid
    + GetName(): string
    
    + GetAdmin(): User?
    + GetMemberRights(): Dictionary<User, SingleMemberRights>
    + GetChildUserGroups(): UserGroup[]
}
hide UserGroup fields
UserGroup "*" -- "*" UserGroup : < Дочерний узел
Announcement "*" o-- "1..*" UserGroup : > Предназначено

class SingleMemberRights {
    ' todo продумать права
}
hide SingleMemberRights members
UserGroup "1" *-- "*" SingleMemberRights

class User {
    + GetId(): Guid
    
    + GetFirstName(): string
    + SetFirstName(firstName: string): void
    
    + GetSecondName(): string
    + SetSecondName(secondName: string): void
    
    + GetPatronymic(): string?
    + SetPatronymic(patronymic: string?): void
}
hide User fields
UserGroup "*" o-- "0..1" User : < Админ
UserGroup "1..*" o-- "*" User : < Участник
Announcement "*" o-- "1" User : < Автор
AnnouncementCategory "*" o-- "*" User : < Подписан
Survey "*" o-- "*" User : < Проголосовал в 

class Survey extends IAttachment {
     + GetId(): Guid
     
     + GetIsOpen(): bool
     + GetIsAnonymous(): bool
     + GetIsMultipleChoiceAllowed(): bool
     
     + GetAutoClosingAt(): DateTime?
     + GetExpectsAutoClosing(): bool
     
     + GetQuestions(): Question[]
     
     + GetVotersCount(): int
     
     + Close(): void
}
hide Survey fields

class Question {
    + GetId(): Guid
    
    + GetContent(): string
    + GetVotersCount(): int
    
    + GetAnswers(): Answer[]
}
hide Question fields
Survey "1" *-- "1..*" Question

class AnswerBase {
    + GetId(): Guid
    + GetContent(): string
    + abstract GetVotersCount(): int
}
hide AnswerBase fields
Question "1" *-- "2..*" AnswerBase

class Answer extends AnswerBase {
    - _voters: User[]
    
    + GetVoters(): User[]
    + GetVotersCount(): int
    
    + Vote (user: User): void
}
User "*" --o "*" Answer : > Проголосовал за

class AnonymousAnswer extends AnswerBase {
    - _votersCount: int

    + GetVotersCount(): int
    + Vote(): void
}



@enduml
