@startuml
'https://plantuml.com/class-diagram

'left to right direction

hide methods

class Announcement {
    Id: Guid
    Content: string
    
    ExpectsAutoHiding: bool
    AutoHidingAt: DateTime?
    
    ExpectsAutoPublishing: bool
    AutoPublishingAt: DateTime?
    
    IsPublished: bool
    PublishedAt: DateTime?
    
    IsHidden: bool    
    HiddenAt: DateTime?
    
    Author: User
    
    Categories: AnnouncementCategory[]?
    
    Files: File[]?
    Survey: Survey?
    
    UserGroups: UserGroup[]
}

class AnnouncementCategory {
    Id: Guid
    Name: string
    
    Subscribers: User[]
}
Announcement "*" o-- "*" AnnouncementCategory

class File {
    Id: Guid
    Name: string
    
    Hash: string
    LinksCount: int
}
Announcement "1..*" o-- "*" File

class UserGroup {
    Id: Guid
    Name: string
    
    Admin: User?
    MemberRights: Dictionary<User, MemberRights>
    
    Children: UserGroup[]?
}
UserGroup "0..1" -- "*" UserGroup : < Дочерний узел
Announcement "*" o-- "1..*" UserGroup : > Предназначено

class MemberRights {
    Id: Guid
    ' todo продумать права
}
UserGroup "1" *-- "*" MemberRights

class User {
    Id: Guid
    Name: string
    SecondName: string
    Patronymic: string?
}
UserGroup "*" o-- "0..1" User : < Админ
UserGroup "1..*" o-- "*" User : < Участник
Announcement "*" o-- "1" User : < Автор
AnnouncementCategory "*" o-- "*" User : < Подписан
Survey "*" o-- "*" User : < Проголосовал в 

class Survey {
    Id: Guid
    
    IsOpen: bool
    IsAnonymous: bool
    IsMultipleChoiceAllowed: bool
    
    ExpectsAutoClosing: bool
    AutoClosingAt: DateTime?
    
    Questions: Question[]
    
    Voters: User[]?
}
Announcement "1" *-- "1" Survey
'User "*" -- "*" Survey

class Question {
    Id: Guid
    Content: string
    VotersCount: int
    
    Answers: Answer[]
}
Survey "1" *-- "1..*" Question

class Answer {
    Id: Guid
    Content: string
    
    VotersCount: int
    Voters: User[]?
}
Question "1" *-- "2..*" Answer
User "*" --o "*" Answer : > Проголосовал за



@enduml
