@startuml
'https://plantuml.com/class-diagram

hide methods

entity "Пользователь" as user {
    Фамилия
    Имя
    Отчество
}

entity "Объявление" as notification { 
    Текст
    Флаг автоматического сокрытия
    Срок автоматического сокрытия
    Флаг отложенной публикации
    Срок отложенной публикации
}
notification }o--|| user : Автор

entity "Вложение" as attachment { 
    Название
    Содержимое
    Количество ссылок
}
notification }|--o{ attachment

entity "Опрос" as survey {
    Размер аудитории
    Флаг анонимности
    Флаг возможности выбора нескольких вариантов ответов
    Флаг ограничения времени голосования
    Срок окончания времени голосования
}
notification ||--o| survey

entity "Вопрос" as question {
    Текст вопроса
    Количество проголосовавших
}
survey ||--|{ question

entity "Вариант ответа" as answer  {
    Текст
    Количество проголосовавших
}
question ||--{ answer
user }o--o{ answer : Выбрал

entity "Группа пользователей" as userGroup { 
    Название
}
notification }o--|{ userGroup
user }|--|{ userGroup : Участники
user }o--|{ userGroup : Администратор


@enduml
