@startuml
'https://plantuml.com/class-diagram

hide methods

entity "Пользователь" as user {
    Фамилия
    Имя
    Отчество
}

entity "Объявление" as announcement { 
    Текст
    Флаг скрытой публикации
    Флаг автоматического сокрытия
    Срок автоматического сокрытия
    Флаг отложенной публикации
    Срок отложенной публикации
    Момент публикации
    Момент сокрытия
}
announcement }o--|| user : < Автор

entity "Категория" as category {
    Название
}
announcement }o--o{ category
user }o-up-o{ category : > Подписан

entity "Файл" as attachedFile { 
    Название
    Содержимое
    Хэш
    Количество ссылок
}
announcement }|--o{ attachedFile

entity "Опрос" as survey {
    Флаг открытости
    Флаг анонимности
    Флаг множественного выбора
    Флаг ограничения времени голосования
    Срок окончания времени голосования
}
announcement ||--o| survey
user }o--o{ survey : > Проголосовал в

entity "Вопрос" as question {
    Текст вопроса
    Количество проголосовавших
}
survey ||--|{ question

entity "Вариант ответа" as answer {
    Текст вариант ответа
    Количество проголосовавших
}
question ||--{ "2..*" answer
user }o--o{ answer : > Выбрал

entity "Группа пользователей" as userGroup { 
    Название
}
announcement }o--|{ userGroup : > Предназначено
user }o--|{ userGroup : > Участник
user |o-right-o{ userGroup : > Администратор
userGroup |o--o{ userGroup : Подчинена максимум одной \n Является родителем любого количества

entity "Права участника группы" as memberRights {}
hide memberRights members
user ||--|{ memberRights
userGroup ||--o{ memberRights



@enduml
