@startuml
'https://plantuml.com/deployment-diagram

left to right direction

rectangle "Локальная сеть" {
    node "Сервер приложения" as server_node {
        component "Сервер" as app_server
    }
    
    node "Сервер основной базы данных" {
        database "База данных" as announcements_db
    }
    app_server -- announcements_db : tcp / ip
    
    node "Сервер базы учетных данных" {
        database "База данных" as accounts_db
    }
    app_server -- accounts_db : tcp / ip
}

cloud "Интернет" as internet
app_server -left- internet : http / https

node "Мобильный клиент" as mobile_client {
    component "Мобильное приложение" as mobile_app
}
internet -- mobile_app : http / https

node "Десктопный клиент" as desktop_client {
    component "Браузер" as browser
}
internet -- browser : http / https

@enduml