@startuml
'https://plantuml.com/deployment-diagram



'left to right direction

node "VPS" {
    component "API Шлюз" as api_gateway
    
    component "Сервис уведомлений" as notifications_service {
        component "gotify"
    }
       
    
    database "БД сервиса системы\nинформирования" as information_system_service_db
    
    component "Сервис системы\nинформирования" as information_system_service
    api_gateway <-up-> information_system_service : http
'    information_system_service_db <-left-> information_system_service : tcp / ip
    information_system_service_db <-down-> information_system_service : tcp / ip
    notifications_service <--- information_system_service : http
    
    
    component "Сервис аутентификации" as auth_service
    api_gateway <-up-> auth_service : http
    
    database "БД сервиса\nаутентификации" as auth_service_db
'    auth_service_db <-right-> auth_service : tcp/ip
    auth_service_db <-down-> auth_service : tcp/ip
    
    
    
    collections "Сервисы,\nразработанные коллегой" as side_services
    api_gateway <-right-> side_services
}



node "Мобильный клиент" as mobile_client {
    component "Мобильное приложение" as mobile_app
}
api_gateway <--> mobile_client : http / https
notifications_service --> mobile_client : websocket
notifications_service <-- mobile_client : http

node "Десктопный клиент" as desktop_client {
    component "Браузер" as browser
}
api_gateway <--> desktop_client : http / https
'notifications_service <-- desktop_client : http
'notifications_service --> desktop_client : websocket


@enduml