@startuml
'https://plantuml.com/class-diagram

hide methods

entity "Пользователь" as user {
    Фамилия
    Имя
    Отчество
}

entity "Объявление" as announcement { 
    Текст
    Размер аудитории
    Флаг скрытой публикации
    Флаг автоматического сокрытия
    Срок автоматического сокрытия
    Флаг отложенной публикации
    Срок отложенной публикации
    Момент публикации
    Момент сокрытия
}
announcement }o--|| user : < Автор
announcement }o--|{ user : > Предназначено

entity "Опрос" as survey {
    Размер аудитории
    Флаг открытости
    Флаг анонимности
    Флаг ограничения времени голосования
    Срок окончания времени голосования
    Флаг блокирования результатов\n        до окончания голосования
}
announcement ||--o| survey : < Прикреплен
user }o--o{ survey : > Проголосовал в

entity "Вопрос" as question {
    Текст вопроса
    Количество проголосовавших
    Флаг множественного выбора
}
survey ||--|{ question

entity "Вариант ответа" as answer {
    Текст вариант ответа
    Количество проголосовавших
}
question ||--{ "2..*" answer
user }o--o{ answer : > Выбрал

entity "Группа пользователей" as userGroup { 
    Название
}
user }o--|{ userGroup : > Участник
user |o-right-o{ userGroup : > Администратор
userGroup }o--o{ userGroup : Подчинена любому количеству \n Является родителем любого количества

entity "Права участника группы" as memberRights {}
hide memberRights members
user ||--|{ memberRights
userGroup ||--o{ memberRights



@enduml
