#!/usr/bin/env bash
#
# Generated by: https://openapi-generator.tech
#

dotnet restore src/BulletInBoardServer.Controllers.CategoriesController/ && \
    dotnet build src/BulletInBoardServer.Controllers.CategoriesController/ && \
    echo "Now, run the following to start the project: dotnet run -p src/BulletInBoardServer.Controllers.CategoriesController/BulletInBoardServer.Controllers.CategoriesController.csproj --launch-profile web"
