#!/usr/bin/env bash
#
# Generated by: https://openapi-generator.tech
#

dotnet restore src/BulletInBoardServer.Controllers.UsersController/ && \
    dotnet build src/BulletInBoardServer.Controllers.UsersController/ && \
    echo "Now, run the following to start the project: dotnet run -p src/BulletInBoardServer.Controllers.UsersController/BulletInBoardServer.Controllers.UsersController.csproj --launch-profile web"
