openapi: 3.0.3
info:
  title: Общие схемы для API шлюза
  description: Общие схемы для API шлюза
  version: 0.0.1
servers:
  - url: '/api'
paths:

components:
  schemas:
    identifiers:
      type: array
      nullable: true
      items:
        type: string
        format: uuid
    