openapi: 3.0.3
info:
  title: API Шлюз. Файлы
  description: API шлюза для управления файлами
  version: 1.0.0
servers:
  - url: '/api'
paths:

components:
  schemas:
    fileSummaryDto:
      type: object
      properties:
        id:
          description: Идентификатор файла
          type: string
          format: uuid
        name:
          description: Название файла
          type: string
        type:
          description: Тип файла
          type: string
          enum:
            - mediafile # Медиафайл отображается в объявлении сразу
            - file # Обычный файл загружается вручную
