openapi: 3.0.3
info:
  title: Ping
  description: Проверка доступности сервиса
  version: 1.0.0
servers:
  - url: 'https://localhost:8080'
paths:
  /ping:
    get:
      responses: 
        200:
          description: Ok
          content:
            text/plain:
              schema: 
                type: string
                example: pong
