openapi: 3.0.3
info:
  title: Ping
  description: Проверка доступности сервиса
  version: 1.0.0
servers:
  - url: '/api'
paths:
  /ping:
    get:
      tags: [ Ping ]
      operationId: ping
      responses:
        200:
          description: Ok
          content:
            text/plain:
              schema:
                type: string
                example: pong
