openapi: 3.0.3
info:
  title: API Шлюз. Опросы
  description: API шлюза для управления опросами
  version: 1.0.0
servers:
  - url: '/api'
tags:
  - name: Surveys
    description: API управления опросами
paths:
  # survey
  /surveys/create:
    post:
      operationId: createSurvey
      summary: Создать опрос
      parameters:
        - in: header
          name: X-User-Id
          required: true
          schema:
            description: Идентификатор пользователя
            type: string
            format: uuid
        - in: header
          name: rootUserGroupId
          schema:
            type: string
            format: uuid
          required: true
          description: Корневая группа пользователей, от которой запрашивается операция
      tags: [ Surveys ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/createSurveyDto'
      responses:
        201:
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/surveyIdentifierDto'
        401:
          description: Unauthorized
        403:
          description: Forbidden
          content:
            application/json:
              schema:
                type: object
                title: createSurveyForbidden
                properties:
                  code:
                    # createSurveyForbidden
                    $ref: '#/components/schemas/createSurveyResponses'
        500:
          description: Internal Server Error
  
  /surveys/close-survey:
    post:
      operationId: closeSurvey
      summary: Закрыть опрос
      parameters:
        - in: header
          name: X-User-Id
          required: true
          schema:
            description: Идентификатор пользователя
            type: string
            format: uuid
      tags: [ Surveys ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/surveyIdentifierDto'
      responses:
        200:
          description: Ok
        400:
          # Некорректный формат идентификатора
          description: Bad Request
        401:
          description: Unauthorized
        403:
          description: Forbidden
          content:
            application/json:
              schema:
                type: object
                title: closeSurveyForbidden
                properties:
                  code:
                    # surveyClosingForbidden
                    $ref: '#/components/schemas/closeSurveyResponses'
        404:
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                title: closeSurveyNotFound
                properties:
                  code:
                    # surveyDoesNotExist
                    $ref: '#/components/schemas/closeSurveyResponses'
        409:
          description: Conflict
          content:
            application/json:
              schema:
                type: object
                title: closeSurveyConflict
                properties:
                  code:
                    # surveyAlreadyClosed
                    $ref: '#/components/schemas/closeSurveyResponses'
        500:
          description: Internal Server Error
  
  /surveys/download-results/{id}/{filetype}:
    get:
      operationId: downloadSurveyResults
      tags: [ Surveys ]
      summary: Скачать результаты опроса
      parameters:
        - in: header
          name: X-User-Id
          required: true
          schema:
            description: Идентификатор пользователя
            type: string
            format: uuid
        - in: path
          name: id
          schema:
            type: string
            format: uuid
          required: true
          description: Идентификатор опроса
        - in: path
          name: filetype
          schema: 
            type: string
          description: Тип файла с результатами опроса
          required: true
      responses:
        200:
          description: Ok
          content:
            application/octet-stream:
              schema:
                type: object
                title: downloadSurveyResultsOk
                properties:
                  content:
                    type: string
                    format: binary
        400:
          # Нижеописанные коды + некорректный формат идентификатора
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                title: downloadSurveyResultsForbidden
                properties:
                  code:
                    # fileTypeNotSupported
                    $ref: '#/components/schemas/downloadSurveyResultsResponses'
        401:
          description: Unauthorized
        403:
          description: Forbidden
          content:
            application/json:
              schema:
                type: object
                title: downloadSurveyResultsForbidden
                properties:
                  code:
                    # surveyResultsDownloadingForbidden
                    $ref: '#/components/schemas/downloadSurveyResultsResponses'
        404:
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                title: downloadSurveyResultsNotFound
                properties:
                  code:
                    # surveyDoesNotExist
                    $ref: '#/components/schemas/downloadSurveyResultsResponses'
        409:
          description: Conflict
          content:
            application/json:
              schema:
                type: object
                title: downloadSurveyResultsConflict
                properties:
                  code:
                    # announcementWithSurveyNotYetPublished
                    $ref: '#/components/schemas/downloadSurveyResultsResponses'
        500:
          description: Internal Server Error
  
  /surveys/vote:
    post:
      operationId: voteInSurvey
      summary: Проголосовать в опросе
      parameters:
        - in: header
          name: X-User-Id
          required: true
          schema:
            description: Идентификатор пользователя
            type: string
            format: uuid
      tags: [ Surveys ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/voteInSurveyDto'
      responses:
        200:
          description: Ok
        400:
          # Некорректный формат идентификатора
          description: Bad Request
        401:
          description: Unauthorized
        403:
          description: Forbidden
          content:
            application/json:
              schema:
                type: object
                title: voteInQuestionForbidden
                properties:
                  code:
                    # votingForbidden
                    $ref: '#/components/schemas/voteInSurveyResponses'
        404:
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                title: voteInQuestionNotFound
                properties:
                  code:
                    # surveyDoesNotExist
                    $ref: '#/components/schemas/voteInSurveyResponses'
        409:
          description: Conflict
          content:
            application/json:
              schema:
                type: object
                title: voteInQuestionConflict
                properties:
                  code:
                    # surveyClosed
                    # answerAlreadyVoted
                    # cannotSelectMultipleAnswersInSingleChoiceQuestion
                    # presentedQuestionsDoesntMatchSurveyQuestions
                    # presentedVotesDoesntMatchQuestionAnswers
                    $ref: '#/components/schemas/voteInSurveyResponses'
        500:
          description: Internal Server Error

components:
  schemas:
    ### public
    # survey
    createSurveyDto:
      type: object
      properties:
        questions:
          description: Вопросы опроса
          type: array
          minItems: 1
          items:
            $ref: '#/components/schemas/createQuestionDto'
        isAnonymous:
          description: Анонимен ли опрос
          type: boolean
        resultsOpenBeforeClosing:
          description: Открыты ли результаты опроса до закрытия
          type: boolean
        voteUntil:
          description: Срок окончания голосования. Null, если голосование не ограничено по сроку
          type: string
          format: date-time
          nullable: true
    
    surveyDetailsDto:
      type: object
      properties:
        id:
          description: Идентификатор опроса
          type: string
          format: uuid
        isVotedByRequester:
          description: Проголосовал ли в опросе пользователь, запросивший детали опроса
          type: boolean
        isOpen:
          description: Открыт ли опрос
          type: boolean
          default: true
        isAnonymous:
          description: Анонимен ли опрос
          type: boolean
          default: false
        resultsOpenBeforeClosing:
          description: Открыты ли результаты опроса до закрытия
          type: boolean
        voters:
          description: Проголосовавшие в опросе пользователи
          type: array
          items:
            $ref: './users-api.yaml#/components/schemas/userSummaryDto'
        autoClosingAt:
          description: Время окончания голосования (если задано)
          type: string
          format: date-time
          nullable: true
        voteFinishedAt:
          description: Фактическое время окончания голосования (если голосование завершено)
          type: string
          format: date-time
          nullable: true
        questions:
          description: Вопросы опроса
          type: array
          items:
            $ref: '#/components/schemas/questionDetailsDto'
          minItems: 1
    
    surveyIdentifierDto:
      description: Идентификатор опроса
      type: string
      format: uuid
    
    downloadSurveyResultsRequestDto:
      description: DTO для запроса выгрузки результатов опроса
      type: object
      required:
        - surveyId
        - fileType
      properties:
        surveyId:
          $ref: '#/components/schemas/surveyIdentifierDto'
        fileType:
          description: Тип файла с результатами опроса
          type: string
    
    voteInSurveyDto:
      description: DTO для голосования в опросе
      type: object
      properties:
        surveyId:
          description: Идентификатор опроса
          type: string
          format: uuid
        questionVotes:
          description: Голоса за варианты ответов в каждом вопросе опроса
          type: array
          items:
            $ref: '#/components/schemas/voteInQuestionDto'
          minItems: 1
    
    voteInQuestionDto:
      description: DTO для голосования в вопросе опроса
      type: object
      properties:
        questionId:
          description: Идентификатор вопроса
          type: string
          format: uuid
        answerIds:
          description: Массив идентификаторов вариантов ответов
          type: array
          minItems: 1
          items:
            type: string
            format: uuid
            uniqueItems: true

    surveyResultsDto:
      description: Результаты опроса
      type: object
      properties:
        voters:
          $ref: '#/components/schemas/votersDto'
        answerResults:
          $ref: '#/components/schemas/answerResultsDto'

    # question
    createQuestionDto:
      type: object
      properties:
        serial:
          description: Порядковый номер вопроса в списке вопросов
          type: integer
          minimum: 0
        content:
          description: Содержимое вопроса
          type: string
        isMultipleChoiceAllowed:
          description: Доступен ли выбор нескольких вариантов ответов
          type: boolean
        answers:
          description: Варианты ответов
          type: array
          minItems: 2
          items:
            $ref: '#/components/schemas/createAnswerDto'

    questionDetailsDto:
      type: object
      properties:
        id:
          description: Идентификатор вопроса
          type: string
          format: uuid
        serial:
          description: Порядковый номер вопроса в списке вопросов
          type: integer
          minimum: 0
        content:
          description: Текстовое содержимое вопроса
          type: string
        isMultipleChoiceAllowed:
          description: Разрешен ли множественный выбор
          type: boolean
          default: false
        answers:
          description: Варианты ответов опроса
          type: array
          items:
            $ref: '#/components/schemas/questionAnswerDetailsDto'
          minItems: 2
    
    questionAnswerDetailsDto:
      type: object
      properties:
        id:
          description: Идентификатор варианта ответа
          type: string
          format: uuid
        serial:
          description: Порядковый номер варианта ответов в списке вариантов ответов
          type: integer
          minimum: 0
        content:
          description: Текстовое содержимое варианта ответа
          type: string
        voters:
          description: Список проголосовавших за вариант ответа пользователей. Пустой, если вариант ответа относится к анонимному опросу
          type: array
          items:
            $ref: './users-api.yaml#/components/schemas/userSummaryDto'
        votersAmount:
          description: Количество пользователей, проголосовавших за вариант ответа
          type: integer
          minimum: 0
    
    # answer
    createAnswerDto:
      type: object
      properties:
        serial:
          description: Порядковый номер варианта ответа в списке вариантов ответов
          type: integer
          minimum: 0
        content:
          description: текстовое содержимое варианта ответа
          type: string
    
    ### private
    votersDto:
      type: array
      items:
        $ref: '#/components/schemas/voterDto'
    
    voterDto:
      type: object
      properties:
        id:
          description: Числовой идентификатор пользователя
          type: integer
        name:
          description: Имя пользователя
          type: string
    
    answerResultsDto:
      type: array
      items:
        $ref: '#/components/schemas/answerResultDto'
    
    answerResultDto:
      type: object
      properties:
        questionId:
          description: Идентификатор варианта ответа
          type: string
          format: uuid
        voterIds:
          description: Числовые идентификаторы проголосовавших пользователей
          type: array
          items:
            type: integer

    createSurveyResponses:
      type: string
      enum:
        # 403
        - createSurveyForbidden
        # 409
        - surveyContainsQuestionSerialsDuplicates
        - questionContainsAnswersSerialsDuplicates
      description: >
        Ответы:
          createSurveyForbidden - Пользователь не имеет права создать опрос
          surveyContainsQuestionSerialsDuplicates - Опрос содержит вопросы с одинаковыми порядковыми номерами
          questionContainsAnswersSerialsDuplicates - Вопрос содержит варианты ответов с повторяющимися порядковыми номерами

    getSurveyDetailsResponses:
      type: string
      enum:
        # 403
        - detailsAccessForbidden
        # 404
        - surveyDoesNotExist
      description: >
        Ответы:
          detailsAccessForbidden - Пользователь не имеет права просмотреть подробности этого опроса
          surveyDoesNotExist - Опрос не существует

    closeSurveyResponses:
      type: string
      enum:
        # 403
        - surveyClosingForbidden
        # 404
        - surveyDoesNotExist
        # 409
        - surveyAlreadyClosed
      description: >
        Ответы:
          surveyClosingForbidden - Пользователь не имеет права закрыть этот опрос
          surveyDoesNotExist - Опрос не существует
          surveyAlreadyClosed - Опрос уже закрыт

    getSurveysResultsResponses:
      type: string
      enum:
        # 403
        - surveyResultsAccessForbidden
        # 404
        - surveyDoesNotExist
        # 409
        - announcementWithSurveyNotYetPublished
      description: >
        Ответы:
          surveyResultsAccessForbidden - Пользователь не имеет права получить результаты этого опроса
          surveyDoesNotExist - Опрос не существует
          announcementWithSurveyNotYetPublished - Объявление с опросом еще не опубликовано

    downloadSurveyResultsResponses:
      type: string
      enum:
        # 400
        - fileTypeNotSupported
        # 403
        - surveyResultsDownloadingForbidden
        # 404
        - surveyDoesNotExist
        # 409
        - announcementWithSurveyNotYetPublished
      description: >
        Ответы:
          fileTypeNotSupported - Тип файла с результатами опроса не поддерживается
          surveyResultsDownloadingForbidden - Пользователь не имеет права выгрузить результаты этого опроса
          surveyDoesNotExist - Опрос не существует
          announcementWithSurveyNotYetPublished - Объявление с опросом еще не опубликовано

    voteInSurveyResponses:
      type: string
      enum:
        # 403
        - votingForbidden
        # 404
        - surveyDoesNotExist
        # 409
        - surveyClosed
        - surveyAlreadyVoted
        - cannotSelectMultipleAnswersInSingleChoiceQuestion
        - presentedQuestionsDoesntMatchSurveyQuestions
        - presentedVotesDoesntMatchQuestionAnswers
      description: >
        Ответы:
          votingForbidden - Пользователь не имеет права голосовать в опросе
          surveyDoesNotExist - Опрос не существует
          surveyClosed - Опрос закрыт
          surveyAlreadyVoted - Голос в опросе уже отдан
          cannotSelectMultipleAnswersInSingleChoiceQuestion - В вопросе с единственным выбором нельзя выбрать несколько вариантов ответов
          presentedQuestionsDoesntMatchSurveyQuestions - Список представленных вопросов не соответствует фактическому списку вопросов опроса
          presentedVotesDoesntMatchQuestionAnswers - Список выбранных вариантов ответов для одного или нескольких вопросов не включается в список вариантов ответов вопроса

    cancelVoteInQuestionResponses:
      type: string
      enum:
        # 403
        - votingForbidden
        # 404
        - questionDoesNotExist
        # 409
        - surveyClosed
        - surveyNotVoted
      description: >
        Ответы:
          votingForbidden - Пользователь не имеет права голосовать в этом опросе
          questionDoesNotExist - Вопрос не существует
          surveyClosed - Опрос закрыт
          surveyNotVoted - Пользователь не проголосовал в вопросе
