openapi: 3.0.3
info:
  title: API Шлюз. Пользователи
  description: API Шлюз. Пользователи
  version: 0.0.1
servers:
  - url: '/api'
paths:
#  /users/get-usergroups:

components:
  schemas:
    userSummaryDto:
      type: object
      nullable: true
      properties:
        id:
          type: string
          format: uuid
        firstName:
          type: string
        secondName:
          type: string
        patronymic:
          type: string
          nullable: true

    selectableUserSummaryDto:
      type: object
      nullable: true
      properties:
        id:
          type: string
          format: uuid
        firstName:
          type: string
        secondName:
          type: string
        patronymic:
          type: string
          nullable: true
        isSelected:
          type: boolean
