openapi: 3.0.3
info:
  title: API Шлюз. Пользователи
  description: API Шлюз. Пользователи
  version: 1.0.0
paths:

components:
  schemas:
    userSummaryDto:
      type: object
      nullable: true
      properties:
        id:
          description: Идентификатор пользователя
          type: string
          format: uuid
        firstName:
          description: Имя пользователя
          type: string
        secondName:
          description: Фамилия пользователя
          type: string
        patronymic:
          description: Отчество пользователя
          type: string
          nullable: true

    checkableUserSummaryDto:
      type: object
      nullable: true
      properties:
        id:
          description: Идентификатор пользователя
          type: string
          format: uuid
        firstName:
          description: Имя пользователя
          type: string
        secondName:
          description: Фамилия пользователя
          type: string
        patronymic:
          description: Отчество пользователя
          type: string
          nullable: true
        isChecked:
          description: Выбран ли пользователь
          type: boolean
