:: Generated by: https://openapi-generator.tech
::

@echo off

dotnet restore src\BulletInBoardServer.Controllers.UserGroupsController
dotnet build src\BulletInBoardServer.Controllers.UserGroupsController
echo Now, run the following to start the project: dotnet run -p src\BulletInBoardServer.Controllers.UserGroupsController\BulletInBoardServer.Controllers.UserGroupsController.csproj --launch-profile web.
echo.
