openapi: 3.0.3
info:
  title: Схемы объявлений для API Шлюза
  description: Схемы объявлений для API Шлюза
  version: 0.0.1
servers:
  - url: 'https://localhost:8080'
paths:

components:
  schemas:
    createAnnouncementDto:
      type: object
      properties:
        content:
          description: Текстовое содержимое объявления
          type: string
        userGroupIds:
          description: Идентификаторы групп пользователей, для которых создается объявление
          type: array
          items:
            type: string
            format: uuid
          minItems: 1
        categoryIds:
          description: Идентификаторы категорий объявлений
          type: array
          items: 
            type: string
            format: uuid
        surveyId:
          description: Идентификатор опроса, прикрепляемого к объявлению
          type: string
          format: uuid
          nullable: true
          default: null
        fileIds:
          description: Идентификаторы файлов, прикрепляемых к объявлению
          type: array
          items:
            type: string
            format: uuid
          nullable: true
        hideAt:
          description: Срок автоматического сокрытия объявления
          type: string
          format: date-time
          nullable: true
          default: null
        publishAt:
          description: Срок отложенной публикации объявления
          type: string
          format: date-time
          nullable: true
          default: null

    announcementIdentifierDto:
      description: Идентификатор объявления
      type: string
      format: uuid

    announcementSummaryDto:
      type: object
      properties:
        id:
          description: Идентификатор объявления
          type: string
          format: uuid
        author:
          description: Автор объявления
          type: string
        content:
          description: Текстовое содержимое объявления
          type: string
        publishedAt:
          description: Время публикации объявления
          type: string
          format: date-time
        viewers:
          description: Количество просмотревших объявление пользователей
          type: integer
          minimum: 0
        audienceSize:
          description: Размер аудитории объявления
          type: integer
          minimum: 0
        files:
          description: Массив файлов, прикрепленных к объявлению
          type: array
          nullable: true
          items:
            $ref: './file-schemas.yaml#/components/schemas/fileSummaryDto'
        survey:
          $ref: './survey-schemas.yaml#/components/schemas/surveyDetailsDto'

    announcementDetailsDto:
      type: object
      properties:
        content:
          description: Текстовое содержимое объявления
          type: string
        author:
          description: Автор объявления
          type: string
        viewers:
          description: Количество просмотревших объявление пользователей
          type: integer
          minimum: 0
        audienceSize:
          description: Размер аудитории объявления
          type: integer
          minimum: 0
        categoryIds:
          description: Массив идентификаторов категорий объявлений
          type: array
          items:
            $ref: './announcement-category-schemas.yaml#/components/schemas/announcementCategoryDetailsDto'
        files:
          description: Массив файлов, прикрепленных к объявлению
          type: array
          nullable: true
          items:
            $ref: './file-schemas.yaml#/components/schemas/fileSummaryDto'
        survey:
          $ref: './survey-schemas.yaml#/components/schemas/surveyDetailsDto'
        hiddenAt:
          description: Момент сокрытия объявления. Объявление не является скрытым, если null
          type: string
          format: date-time
          nullable: true
          default: null
        hideAt:
          description: Срок автоматического сокрытия объявления. Объявление не будет скрыто автоматически, если null
          type: string
          format: date-time
          nullable: true
          default: null
        publishAt:
          description: Срок отложенной публикации объявления. Объявление не будет опубликовано автоматически, если null
          type: string
          format: date-time
          nullable: true
          default: null
    
    updateAnnouncementDto:
      type: object
      properties:
        id:
          type: string
          format: uuid
          required: true
        content:
          description: Текстовое содержимое объявления
          type: string
          nullable: true
          default: null
        categoryIds:
          description: Массив идентификаторов категорий объявлений
          type: array
          items: 
            type: string
            format: uuid
        userGroupIds:
          description: Идентификаторы групп пользователей, для которых создается объявление
          type: array
          items:
            type: string
            format: uuid
          minItems: 1
          nullable: true
          default: null
        surveyId:
          description: Идентификатор опроса, прикрепляемого к объявлению
          type: string
          format: uuid
          nullable: true
          default: null
        fileIds:
          description: Идентификаторы файлов, прикрепляемых к объявлению
          type: array
          items:
            type: string
            format: uuid
          nullable: true
          default: null
        hideAt:
          description: Срок автоматического сокрытия объявления
          type: string
          format: date-time
          nullable: true
          default: null
        publishAt:
          description: Срок отложенной публикации объявления
          type: string
          format: date-time
          nullable: true
          default: null
    
    