openapi: 3.0.3
info:
  title: Схемы категорий объявлений для API шлюза
  description: Схемы категорий объявлений для API шлюза
  version: 0.0.1
servers:
  - url: 'https://localhost:8080'
paths:
  
components:
  schemas:
    announcementCategoryDetailsDto:
      type: object
      properties: 
        id:
          type: string
          format: uuid
        name:
          type: string
        color:
          type: string
    
    createAnnouncementCategoryDto:
      type: object
      properties:
        name:
          type: string
        colorHex:
          type: string
          format: hex
        
    announcementCategoryIdentifierDto:
      description: Идентификатор категории объявлений
      type: string
      format: uuid
      
    announcementCategoriesListDto:
      type: object
      properties: 
        categories:
          type: array
          items:
            $ref: '#/components/schemas/announcementCategoryDetailsDto'
            
    updateAnnouncementCategoryDto:
      type: object
      properties: 
        id:
          type: string
          format: uuid
        name:
          type: string
          nullable: true
        colorHex:
          type: string
          nullable: true