openapi: 3.0.3
info:
  title: Схемы объявлений для API Шлюза
  description: Схемы объявлений для API Шлюза
  version: 0.0.1
servers:
  - url: 'https://localhost:8080'
paths:
  
components: 
  schemas:
    createNotificationDto:
      type: object
      nullable: false
      properties:
        content:
          description: Текстовое содержимое объявления
          type: string
          nullable: false
        userGroupIds:
          description: Идентификаторы групп пользователей, для которых создается объявление
          type: array
          items:
            type: string
            format: uuid
          minItems: 1
          nullable: false
        surveyId:
          description: Идентификатор опроса, прикрепляемого к объявлению
          type: string
          format: uuid
          nullable: true
          default: null
        fileIds:
          description: Идентификаторы файлов, прикрепляемых к объявлению
          type: array
          items:
            type: string
            format: uuid
          nullable: true
        hideAt:
          description: Срок автоматического сокрытия объявления
          type: string
          format: date-time
          nullable: true
          default: null
        publishAt:
          description: Срок отложенной публикации объявления
          type: string
          format: date-time
          nullable: true
          default: null
      additionalProperties: false

    notificationIdentifier:
      type: object
      nullable: false
      properties:
        notificationId:
          type: string
          format: uuid
          nullable: false
      additionalProperties: false

    notificationSummaryDto:
      type: object
      nullable: false
      properties:
        id:
          description: Идентификатор объявления
          type: string
          format: uuid
          nullable: false
        author:
          description: Автор объявления
          type: string
          nullable: false
        content:
          description: Текстовое содержимое объявления
          type: string
          nullable: false
        publishedAt:
          description: Время публикации объявления
          type: string
          format: date-time
          nullable: false
        viewers:
          description: Количество просмотревших объявление пользователей
          type: integer
          nullable: false
          minimum: 0
        audienceSize:
          description: Размер аудитории объявления
          type: integer
          nullable: false
          minimum: 0
        files:
          description: Массив файлов, прикрепленных к объявлению
          type: array
          nullable: true
          items:
            $ref: './file-schemas.yaml#/components/schemas/fileSummaryDto'
        survey:
          $ref: './survey-schemas.yaml#/components/schemas/surveyDetailsDto'
      additionalProperties: false

    notificationDetailsDto:
      type: object
      nullable: false
      properties:
        content:
          description: Текстовое содержимое объявления
          type: string
          nullable: false
        author:
          description: Автор объявления
          type: string
          nullable: false
        viewers:
          description: Количество просмотревших объявление пользователей
          type: integer
          nullable: false
          minimum: 0
        audienceSize:
          description: Размер аудитории объявления
          type: integer
          nullable: false
          minimum: 0
        files:
          description: Массив файлов, прикрепленных к объявлению
          type: array
          nullable: true
          items:
            $ref: './file-schemas.yaml#/components/schemas/fileSummaryDto'
        survey:
          $ref: './survey-schemas.yaml#/components/schemas/surveyDetailsDto'
        isHidden:
          description: Флаг отражает, скрыто ли объявлению в текущий момент
          type: boolean
          nullable: false
          default: false
        hideAt:
          description: Срок автоматического сокрытия объявления
          type: string
          format: date-time
          nullable: true
          default: null
        publishAt:
          description: Срок отложенной публикации объявления
          type: string
          format: date-time
          nullable: true
          default: null
          
      additionalProperties: false
    
    updateNotificationDto:
      type: object
      nullable: false
      properties:
        id:
          type: string
          format: uuid
          nullable: false
        content:
          description: Текстовое содержимое объявления
          type: string
          nullable: true
          default: null
        userGroupIds:
          description: Идентификаторы групп пользователей, для которых создается объявление
          type: array
          items:
            type: string
            format: uuid
          minItems: 1
          nullable: true
          default: null
        surveyId:
          description: Идентификатор опроса, прикрепляемого к объявлению
          type: string
          format: uuid
          nullable: true
          default: null
        fileIds:
          description: Идентификаторы файлов, прикрепляемых к объявлению
          type: array
          items:
            type: string
            format: uuid
          nullable: true
          default: null
        hideAt:
          description: Срок автоматического сокрытия объявления
          type: string
          format: date-time
          nullable: true
          default: null
        publishAt:
          description: Срок отложенной публикации объявления
          type: string
          format: date-time
          nullable: true
          default: null
      additionalProperties: false
    