openapi: 3.0.3
info:
  title: Схемы пользователей для API Шлюза
  description: Схемы пользователей для API Шлюза
  version: 0.0.1
servers:
  - url: 'https://localhost:8080'
paths:
  
components: 
  schemas: 
    userSummaryDto:
      type: object
      nullable: true
      properties: 
        id:
          type: string
          format: uuid
        firstName:
          type: string
        secondName:
          type: string
        patronymic:
          type: string
     