/*
 * API Шлюз. Группы пользователей
 *
 * API шлюза для управления группами пользователей
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

using System.ComponentModel;
using System.Runtime.Serialization;
using BulletInBoardServer.Controllers.UserGroupsController.Converters;
using Newtonsoft.Json;

namespace BulletInBoardServer.Controllers.UserGroupsController.Models
{ 
        /// <summary>
        /// Ответы:   nameIsNullOrWhitespace - Название группы пользователей null или состоит исключительно из пробельных символов   usergroupCreationForbidden - Пользователь не имеет права создать группу пользователей   usersDoNotExist - В качестве одного или нескольких id пользователей прикреплен несуществующий в базе id   userGroupsDoNotExist - В качестве одного или нескольких id групп пользователей прикреплен несуществующий в базе id   adminCannotBeOrdinaryMember - Идентификатор администратора передан в массиве идентификаторов участников   cyclicDependency - Группа пользователей не может быть создана, так как порождает цикл на графе групп пользователей 
        /// </summary>
        /// <value>Ответы:   nameIsNullOrWhitespace - Название группы пользователей null или состоит исключительно из пробельных символов   usergroupCreationForbidden - Пользователь не имеет права создать группу пользователей   usersDoNotExist - В качестве одного или нескольких id пользователей прикреплен несуществующий в базе id   userGroupsDoNotExist - В качестве одного или нескольких id групп пользователей прикреплен несуществующий в базе id   adminCannotBeOrdinaryMember - Идентификатор администратора передан в массиве идентификаторов участников   cyclicDependency - Группа пользователей не может быть создана, так как порождает цикл на графе групп пользователей </value>
        [TypeConverter(typeof(CustomEnumConverter<CreateUsergroupResponses>))]
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum CreateUsergroupResponses
        {
            
            /// <summary>
            /// Enum NameIsNullOrWhitespace for nameIsNullOrWhitespace
            /// </summary>
            [EnumMember(Value = "nameIsNullOrWhitespace")]
            NameIsNullOrWhitespace = 1,
            
            /// <summary>
            /// Enum UsergroupCreationForbidden for usergroupCreationForbidden
            /// </summary>
            [EnumMember(Value = "usergroupCreationForbidden")]
            UsergroupCreationForbidden = 2,
            
            /// <summary>
            /// Enum UsersDoNotExist for usersDoNotExist
            /// </summary>
            [EnumMember(Value = "usersDoNotExist")]
            UsersDoNotExist = 3,
            
            /// <summary>
            /// Enum UserGroupsDoNotExist for userGroupsDoNotExist
            /// </summary>
            [EnumMember(Value = "userGroupsDoNotExist")]
            UserGroupsDoNotExist = 4,
            
            /// <summary>
            /// Enum AdminCannotBeOrdinaryMember for adminCannotBeOrdinaryMember
            /// </summary>
            [EnumMember(Value = "adminCannotBeOrdinaryMember")]
            AdminCannotBeOrdinaryMember = 5,
            
            /// <summary>
            /// Enum CyclicDependency for cyclicDependency
            /// </summary>
            [EnumMember(Value = "cyclicDependency")]
            CyclicDependency = 6
        }
}
