/*
 * API Шлюз. Группы пользователей
 *
 * API шлюза для управления группами пользователей
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

using System.ComponentModel;
using System.Runtime.Serialization;
using BulletInBoardServer.Controllers.UserGroupsController.Converters;
using Newtonsoft.Json;

namespace BulletInBoardServer.Controllers.UserGroupsController.Models
{ 
        /// <summary>
        /// Ответы:   getAllUsergroupsForbidden - Пользователь не имеет права получать список всех групп пользователей 
        /// </summary>
        /// <value>Ответы:   getAllUsergroupsForbidden - Пользователь не имеет права получать список всех групп пользователей </value>
        [TypeConverter(typeof(CustomEnumConverter<GetAllUsergroupsResponses>))]
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum GetAllUsergroupsResponses
        {
            
            /// <summary>
            /// Enum GetAllUsergroupsForbidden for getAllUsergroupsForbidden
            /// </summary>
            [EnumMember(Value = "getAllUsergroupsForbidden")]
            GetAllUsergroupsForbidden = 1
        }
}
