/*
 * API Шлюз. Группы пользователей
 *
 * API шлюза для управления группами пользователей
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

using System.ComponentModel;
using System.Runtime.Serialization;
using BulletInBoardServer.Controllers.UserGroupsController.Converters;
using Newtonsoft.Json;

namespace BulletInBoardServer.Controllers.UserGroupsController.Models
{ 
        /// <summary>
        /// Ответы:   getOwnedUsergroupsForbidden - Пользователь не имеет права получать список групп пользователей, которыми управляет 
        /// </summary>
        /// <value>Ответы:   getOwnedUsergroupsForbidden - Пользователь не имеет права получать список групп пользователей, которыми управляет </value>
        [TypeConverter(typeof(CustomEnumConverter<GetOwnedUsergroupsResponses>))]
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum GetOwnedUsergroupsResponses
        {
            
            /// <summary>
            /// Enum GetOwnedUsergroupsForbidden for getOwnedUsergroupsForbidden
            /// </summary>
            [EnumMember(Value = "getOwnedUsergroupsForbidden")]
            GetOwnedUsergroupsForbidden = 1
        }
}
