/*
 * API Шлюз. Группы пользователей
 *
 * API шлюза для управления группами пользователей
 *
 * The version of the OpenAPI document: 0.0.3
 *
 * Generated by: https://openapi-generator.tech
 */

using System.ComponentModel;
using System.Runtime.Serialization;
using BulletInBoardServer.Controllers.UserGroupsController.Converters;
using Newtonsoft.Json;

namespace BulletInBoardServer.Controllers.UserGroupsController.Models
{ 
        /// <summary>
        /// Ответы:   getUsergroupHierarchyForbidden - Пользователь не имеет права запрашивать иерархию групп пользователей 
        /// </summary>
        /// <value>Ответы:   getUsergroupHierarchyForbidden - Пользователь не имеет права запрашивать иерархию групп пользователей </value>
        [TypeConverter(typeof(CustomEnumConverter<GetUserHierarchyResponses>))]
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum GetUserHierarchyResponses
        {
            
            /// <summary>
            /// Enum GetUsergroupHierarchyForbidden for getUsergroupHierarchyForbidden
            /// </summary>
            [EnumMember(Value = "getUsergroupHierarchyForbidden")]
            GetUsergroupHierarchyForbidden = 1
        }
}
