/*
 * API Шлюз. Группы пользователей
 *
 * API шлюза для управления группами пользователей
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

using System.ComponentModel;
using System.Runtime.Serialization;
using BulletInBoardServer.Controllers.UserGroupsController.Converters;
using Newtonsoft.Json;

namespace BulletInBoardServer.Controllers.UserGroupsController.Models
{ 
        /// <summary>
        /// Ответы:   nameIsNullOrWhitespace - Имя не содержит символов или содержит исключительно пробельные   updateUsergroupForbidden - Пользователь не имеет права редактировать группу пользователей   usersDoNotExist - В качестве одного или нескольких id пользователей прикреплен несуществующий в базе id   userGroupsDoNotExist - В качестве одного или нескольких id групп пользователей прикреплен несуществующий в базе id   adminCannotBeOrdinaryMember - Идентификатор администратора передан в массиве идентификаторов участников 
        /// </summary>
        /// <value>Ответы:   nameIsNullOrWhitespace - Имя не содержит символов или содержит исключительно пробельные   updateUsergroupForbidden - Пользователь не имеет права редактировать группу пользователей   usersDoNotExist - В качестве одного или нескольких id пользователей прикреплен несуществующий в базе id   userGroupsDoNotExist - В качестве одного или нескольких id групп пользователей прикреплен несуществующий в базе id   adminCannotBeOrdinaryMember - Идентификатор администратора передан в массиве идентификаторов участников </value>
        [TypeConverter(typeof(CustomEnumConverter<UpdateUsergroupResponses>))]
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum UpdateUsergroupResponses
        {
            
            /// <summary>
            /// Enum NameIsNullOrWhitespace for nameIsNullOrWhitespace
            /// </summary>
            [EnumMember(Value = "nameIsNullOrWhitespace")]
            NameIsNullOrWhitespace = 1,
            
            /// <summary>
            /// Enum UpdateUsergroupForbidden for updateUsergroupForbidden
            /// </summary>
            [EnumMember(Value = "updateUsergroupForbidden")]
            UpdateUsergroupForbidden = 2,
            
            /// <summary>
            /// Enum UsersDoNotExist for usersDoNotExist
            /// </summary>
            [EnumMember(Value = "usersDoNotExist")]
            UsersDoNotExist = 3,
            
            /// <summary>
            /// Enum AdminCannotBeOrdinaryMember for adminCannotBeOrdinaryMember
            /// </summary>
            [EnumMember(Value = "adminCannotBeOrdinaryMember")]
            AdminCannotBeOrdinaryMember = 4
        }
}
