/*
 * API Шлюз. Группы пользователей
 *
 * API шлюза для управления группами пользователей
 *
 * The version of the OpenAPI document: 0.0.3
 *
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;

namespace BulletInBoardServer.Controllers.UserGroupsController.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public class UserGroupDetailsDto : IEquatable<UserGroupDetailsDto>
    {
        /// <summary>
        /// Идентификатор группы пользователей
        /// </summary>
        /// <value>Идентификатор группы пользователей</value>
        [DataMember(Name="id", EmitDefaultValue=false)]
        public Guid Id { get; set; }

        /// <summary>
        /// Название группы пользователей
        /// </summary>
        /// <value>Название группы пользователей</value>
        [DataMember(Name="name", EmitDefaultValue=false)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets Admin
        /// </summary>
        [DataMember(Name="admin", EmitDefaultValue=true)]
        public UserSummaryDto Admin { get; set; }

        /// <summary>
        /// Краткая информация об участниках группы пользователей
        /// </summary>
        /// <value>Краткая информация об участниках группы пользователей</value>
        [DataMember(Name="members", EmitDefaultValue=false)]
        public List<UserSummaryWithMemberRightsDto> Members { get; set; }

        /// <summary>
        /// Родительские группы пользователей
        /// </summary>
        /// <value>Родительские группы пользователей</value>
        [DataMember(Name="parents", EmitDefaultValue=false)]
        public List<UserGroupSummaryDto> Parents { get; set; }

        /// <summary>
        /// Дочерние группы пользователей
        /// </summary>
        /// <value>Дочерние группы пользователей</value>
        [DataMember(Name="children", EmitDefaultValue=false)]
        public List<UserGroupSummaryDto> Children { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class UserGroupDetailsDto {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Admin: ").Append(Admin).Append("\n");
            sb.Append("  Members: ").Append(Members).Append("\n");
            sb.Append("  Parents: ").Append(Parents).Append("\n");
            sb.Append("  Children: ").Append(Children).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((UserGroupDetailsDto)obj);
        }

        /// <summary>
        /// Returns true if UserGroupDetailsDto instances are equal
        /// </summary>
        /// <param name="other">Instance of UserGroupDetailsDto to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(UserGroupDetailsDto other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Id == other.Id ||
                    Id != null &&
                    Id.Equals(other.Id)
                ) && 
                (
                    Name == other.Name ||
                    Name != null &&
                    Name.Equals(other.Name)
                ) && 
                (
                    Admin == other.Admin ||
                    Admin != null &&
                    Admin.Equals(other.Admin)
                ) && 
                (
                    Members == other.Members ||
                    Members != null &&
                    other.Members != null &&
                    Members.SequenceEqual(other.Members)
                ) && 
                (
                    Parents == other.Parents ||
                    Parents != null &&
                    other.Parents != null &&
                    Parents.SequenceEqual(other.Parents)
                ) && 
                (
                    Children == other.Children ||
                    Children != null &&
                    other.Children != null &&
                    Children.SequenceEqual(other.Children)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Id != null)
                    hashCode = hashCode * 59 + Id.GetHashCode();
                    if (Name != null)
                    hashCode = hashCode * 59 + Name.GetHashCode();
                    if (Admin != null)
                    hashCode = hashCode * 59 + Admin.GetHashCode();
                    if (Members != null)
                    hashCode = hashCode * 59 + Members.GetHashCode();
                    if (Parents != null)
                    hashCode = hashCode * 59 + Parents.GetHashCode();
                    if (Children != null)
                    hashCode = hashCode * 59 + Children.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(UserGroupDetailsDto left, UserGroupDetailsDto right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(UserGroupDetailsDto left, UserGroupDetailsDto right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
