/*
 * API Шлюз. Группы пользователей
 *
 * API шлюза для управления группами пользователей
 *
 * The version of the OpenAPI document: 0.0.3
 *
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Runtime.Serialization;
using System.Text;

namespace BulletInBoardServer.Controllers.UserGroupsController.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public class UsergroupIdentifierDto : IEquatable<UsergroupIdentifierDto>
    {
        /// <summary>
        /// Gets or Sets AnnouncementId
        /// </summary>
        [DataMember(Name="announcementId", EmitDefaultValue=false)]
        public Guid AnnouncementId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class UsergroupIdentifierDto {\n");
            sb.Append("  AnnouncementId: ").Append(AnnouncementId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((UsergroupIdentifierDto)obj);
        }

        /// <summary>
        /// Returns true if UsergroupIdentifierDto instances are equal
        /// </summary>
        /// <param name="other">Instance of UsergroupIdentifierDto to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(UsergroupIdentifierDto other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    AnnouncementId == other.AnnouncementId ||
                    AnnouncementId != null &&
                    AnnouncementId.Equals(other.AnnouncementId)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (AnnouncementId != null)
                    hashCode = hashCode * 59 + AnnouncementId.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(UsergroupIdentifierDto left, UsergroupIdentifierDto right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(UsergroupIdentifierDto left, UsergroupIdentifierDto right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
