/*
 * API Шлюз. Объявления
 *
 * API шлюза для управления объявлениями
 *
 * The version of the OpenAPI document: 0.0.2
 *
 * Generated by: https://openapi-generator.tech
 */

using System.ComponentModel;
using System.Runtime.Serialization;
using BulletInBoardServer.Controllers.AnnouncementsController.Converters;
using Newtonsoft.Json;

namespace BulletInBoardServer.Controllers.AnnouncementsController.Models
{ 
        /// <summary>
        /// Ответы:    ok - Ок   unauthorized - Пользователь не авторизован для выполнения операции   getDelayedPublishingAnnouncementListResponsesAccessForbidden - Пользователь не имеет права просматривать списки объявлений, ожидающих отложенное сокрытие 
        /// </summary>
        /// <value>Ответы:    ok - Ок   unauthorized - Пользователь не авторизован для выполнения операции   getDelayedPublishingAnnouncementListResponsesAccessForbidden - Пользователь не имеет права просматривать списки объявлений, ожидающих отложенное сокрытие </value>
        [TypeConverter(typeof(CustomEnumConverter<GetDelayedPublishingAnnouncementListResponses>))]
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum GetDelayedPublishingAnnouncementListResponses
        {
            
            /// <summary>
            /// Enum Ok for ok
            /// </summary>
            [EnumMember(Value = "ok")]
            Ok = 1,
            
            /// <summary>
            /// Enum GetDelayedPublishingAnnouncementListResponsesAccessForbidden for getDelayedPublishingAnnouncementListResponsesAccessForbidden
            /// </summary>
            [EnumMember(Value = "getDelayedPublishingAnnouncementListResponsesAccessForbidden")]
            GetDelayedPublishingAnnouncementListResponsesAccessForbidden = 2
        }
}
