/*
 * API Шлюз. Объявления
 *
 * API шлюза для управления объявлениями
 *
 * The version of the OpenAPI document: 0.0.2
 *
 * Generated by: https://openapi-generator.tech
 */

using System.ComponentModel;
using System.Runtime.Serialization;
using BulletInBoardServer.Controllers.AnnouncementsController.Converters;
using Newtonsoft.Json;

namespace BulletInBoardServer.Controllers.AnnouncementsController.Models
{ 
        /// <summary>
        /// Ответы:   hiddenAnnouncementsListAccessForbidden - Пользователь не имеет права просматривать списки скрытых объявлений 
        /// </summary>
        /// <value>Ответы:   hiddenAnnouncementsListAccessForbidden - Пользователь не имеет права просматривать списки скрытых объявлений </value>
        [TypeConverter(typeof(CustomEnumConverter<GetHiddenAnnouncementListResponses>))]
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum GetHiddenAnnouncementListResponses
        {
            
            /// <summary>
            /// Enum HiddenAnnouncementsListAccessForbidden for hiddenAnnouncementsListAccessForbidden
            /// </summary>
            [EnumMember(Value = "hiddenAnnouncementsListAccessForbidden")]
            HiddenAnnouncementsListAccessForbidden = 1
        }
}
