/*
 * API Шлюз. Объявления
 *
 * API шлюза для управления объявлениями
 *
 * The version of the OpenAPI document: 0.0.2
 *
 * Generated by: https://openapi-generator.tech
 */

using System.ComponentModel;
using System.Runtime.Serialization;
using BulletInBoardServer.Controllers.AnnouncementsController.Converters;
using Newtonsoft.Json;

namespace BulletInBoardServer.Controllers.AnnouncementsController.Models
{ 
        /// <summary>
        /// Ответы:    ok - Ок   incorrectIdentifierFormat - Некорректный формат идентификатора   unauthorized - Пользователь не авторизован для выполнения операции   immediatePublishingForbidden - Пользователь не имеет права незамедлительно опубликовать отложенное объявление   announcementDoesNotExist - Объявление не существует   announcementNotDelayed - Объявление не является отложенным 
        /// </summary>
        /// <value>Ответы:    ok - Ок   incorrectIdentifierFormat - Некорректный формат идентификатора   unauthorized - Пользователь не авторизован для выполнения операции   immediatePublishingForbidden - Пользователь не имеет права незамедлительно опубликовать отложенное объявление   announcementDoesNotExist - Объявление не существует   announcementNotDelayed - Объявление не является отложенным </value>
        [TypeConverter(typeof(CustomEnumConverter<PublishImmediatelyDelayedAnnouncementResponses>))]
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum PublishImmediatelyDelayedAnnouncementResponses
        {
            
            /// <summary>
            /// Enum Ok for ok
            /// </summary>
            [EnumMember(Value = "ok")]
            Ok = 1,
            
            /// <summary>
            /// Enum IncorrectIdentifierFormat for incorrectIdentifierFormat
            /// </summary>
            [EnumMember(Value = "incorrectIdentifierFormat")]
            IncorrectIdentifierFormat = 2,
            
            /// <summary>
            /// Enum ImmediatePublishingForbidden for immediatePublishingForbidden
            /// </summary>
            [EnumMember(Value = "immediatePublishingForbidden")]
            ImmediatePublishingForbidden = 3,
            
            /// <summary>
            /// Enum AnnouncementDoesNotExist for announcementDoesNotExist
            /// </summary>
            [EnumMember(Value = "announcementDoesNotExist")]
            AnnouncementDoesNotExist = 4,
            
            /// <summary>
            /// Enum AnnouncementNotDelayed for announcementNotDelayed
            /// </summary>
            [EnumMember(Value = "announcementNotDelayed")]
            AnnouncementNotDelayed = 5
        }
}
