openapi: 3.0.3
info:
  title: API Шлюз. Объявления
  description: API шлюза для управления объявлениями
  version: 0.0.1
servers:
  - url: 'https://localhost:8080'
paths:
  # todo продумать 403 api объявлений
  
  # общие операции
  /notifications/create:
    post:
      tags: [ Общие операции ]
      operationId: createNotification
      summary: Создать объявление
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './schemas/notification-schemas.yaml#/components/schemas/createNotificationDto'
      responses: # todo перевести текст в enum
        201:
          description: Created
          content:
            application/json:
              schema:
                $ref: './schemas/notification-schemas.yaml#/components/schemas/notificationIdentifierDto'
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                type: string
                description: Список групп пользователей null или пустой
                example: Список групп пользователей null или пустой
        404:
          description: Not Found
          content:
            application/json:
              schema:
                oneOf:
                  - type: string
                    description: В качестве одного из id файлов прикреплен несуществующий в базе id
                  - type: string
                    description: В качестве id опроса прикреплен несуществующий в базе id
        409:
          description: Conflict
          content:
            application/json:
              schema:
                oneOf:
                  - type: string
                    description: Нельзя прикрепить к объявлению и файлы, и опрос
                  - type: string
                    description: Момент автоматического сокрытия наступит до момента создания объявления
                  - type: string
                    description: Момент отложенной публикации наступит до момента создания объявления
                  - type: string
                    description: Момент отложенной публикации наступит после момента автоматического сокрытия
  
  /notifications/get-details:
    get:
      tags: [ Общие операции ]
      operationId: getNotificationDetails
      summary: Получить подробности о выбранном объявлении
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './schemas/notification-schemas.yaml#/components/schemas/notificationIdentifierDto'
      responses: # todo перевести текст в enum
        200:
          description: Ok
          content:
            application/json:
              schema:
                $ref: './schemas/notification-schemas.yaml#/components/schemas/notificationDetailsDto'
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: './schemas/common-schemas.yaml#/components/schemas/incorrectIdentifierFormat'
        404:
          description: Not Found
  
  /notifications/update:
    put:
      tags: [ Общие операции ]
      operationId: updateNotification
      summary: Редактировать объявление
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './schemas/notification-schemas.yaml#/components/schemas/updateNotificationDto'
      responses: # todo перевести текст в enum
        200:
          description: Ok
          content:
            application/json:
              schema:
                $ref: './schemas/notification-schemas.yaml#/components/schemas/notificationIdentifierDto'
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                oneOf:
                  - type: string
                    description: Список групп пользователей null или пустой
                    example: Список групп пользователей null или пустой
                  - type: string
                    description: Некорректный формат идентификатора
                    example: Некорректный формат идентификатора
        404:
          description: Not Found
          content:
            application/json:
              schema:
                oneOf:
                  - type: string
                    description: В качестве одного из id файлов прикреплен несуществующий в базе id
                  - type: string
                    description: В качестве id опроса прикреплен несуществующий в базе id
        409:
          description: Conflict
          content:
            application/json:
              schema:
                oneOf:
                  - type: string
                    description: Нельзя прикрепить к объявлению и файлы, и опрос
                  - type: string
                    description: Момент автоматического сокрытия наступит до момента создания объявления
                  - type: string
                    description: Момент отложенной публикации наступит до момента создания объявления
                  - type: string
                    description: Момент отложенной публикации наступит после момента автоматического сокрытия
  
  /notifications/delete:
    delete:
      tags: [ Общие операции ]
      operationId: deleteNotification
      summary: Удалить объявление
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './schemas/notification-schemas.yaml#/components/schemas/notificationIdentifierDto'
      responses:
        200:
          description: Ok
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: './schemas/common-schemas.yaml#/components/schemas/incorrectIdentifierFormat'
        404:
          description: Not Found
  
  # опубликованные объявления  
  /notifications/posted/get-list: # todo учесть получение ограниченного набора
    get:
      tags: [ Опубликованные объявления ]
      operationId: getPostedNotificationList
      summary: Получить список опубликованных объявлений
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: './schemas/notification-schemas.yaml#/components/schemas/notificationSummaryDto'
  
  /notifications/posted/hide:
    post:
      tags: [ Опубликованные объявления ]
      operationId: hideNotification
      summary: Скрыть опубликованное объявление
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './schemas/notification-schemas.yaml#/components/schemas/notificationIdentifierDto'
      responses: # todo перевести текст в enum
        200:
          description: Ok
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: './schemas/common-schemas.yaml#/components/schemas/incorrectIdentifierFormat'
        404:
          description: Not Found
        409:
          description: Conflict
          content:
            application/json:
              schema:
                oneOf:
                  - description: Объявление уже скрыто
                    type: string
                  - description: Объявление еще не опубликовано
                    type: string
  
  # скрытые объявления
  /notifications/hidden/get-list: # todo учесть получение ограниченного набора 
    get:
      tags: [ Скрытые объявления ]
      operationId: getHiddenNotificationList
      summary: Получить список скрытых объявлений
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: './schemas/notification-schemas.yaml#/components/schemas/notificationSummaryDto'
  
  /notifications/hidden/unhide:
    post:
      tags: [ Скрытые объявления ]
      operationId: unhideHiddenNotification
      summary: Восстановить скрытое объявление
      requestBody:
        content:
          application/json:
            schema:
              $ref: './schemas/notification-schemas.yaml#/components/schemas/notificationIdentifierDto'
      responses: # todo перевести текст в enum
        200:
          description: Ok
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: './schemas/common-schemas.yaml#/components/schemas/incorrectIdentifierFormat'
        404:
          description: Not Found
        409:
          description: Conflict
          content:
            application/json:
              schema:
                description: Объявление не является скрытым
                type: string
                example: Объявление не является скрытым
  
  # отложенные объявления
  /notifications/delayed/get-list: # todo учесть получение ограниченного набора
    get:
      tags: [ Отложенные объявления ]
      operationId: getDelayedNotificationList
      summary: Получить список отложенных объявлений
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: './schemas/notification-schemas.yaml#/components/schemas/notificationSummaryDto'
  
  /notifications/delayed/publish-immediately:
    post:
      tags: [ Отложенные объявления ]
      operationId: publishImmediatelyDelayedNotification
      summary: Сразу опубликовать отложенное объявление
      requestBody:
        content:
          application/json:
            schema:
              $ref: './schemas/notification-schemas.yaml#/components/schemas/notificationIdentifierDto'
      responses: # todo перевести текст в enum
        200:
          description: Ok
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: './schemas/common-schemas.yaml#/components/schemas/incorrectIdentifierFormat'
        404:
          description: Not Found
        409:
          description: Conflict
          content:
            application/json:
              schema:
                description: Объявление не является отложенным
                type: string
                example: Объявление не является отложенным
      
      