openapi: 3.0.3
info:
  title: API Шлюз. Опросы
  description: API шлюза для управления опросами
  version: 0.0.1
servers:
  - url: 'https://localhost:8080'
paths:
  # survey
  /surveys/create:
    post:
      operationId: createSurvey
      summary: Создать опрос
      tags: [ Опрос ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './schemas/survey-schemas.yaml#/components/schemas/createSurveyDto'
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                $ref: './schemas/survey-schemas.yaml#/components/schemas/surveyIdentifierDto'
        403:
          description: Forbidden
          content:
            application/json:
              schema:
                description: Пользователь не имеет права создавать опросы
        409: # todo продумать
          description: Conflict
  
  #  /surveys/get-summary: 
  #    get:
  #      operationId: getSurveySummary
  #      summary: Получить детали выбранного опроса
  #      tags: [Опрос]
  #      requestBody:
  #        content:
  #          application/json:
  #            schema:
  #              $ref: './schemas/survey-schemas.yaml#/components/schemas/questionIdentifier'
  #      responses:
  #        200:
  #          description: Ok
  #          content: 
  #            application/json:
  #              schema:
  #                $ref: './schemas/survey-schemas.yaml#/components/schemas/surveySummaryDto'
  #        400:
  #          description: Bad Request
  #          content:
  #            application/json:
  #              schema:
  #                $ref: './schemas/common-schemas.yaml#/components/schemas/incorrectIdentifierFormat'
  #        403:
  #          description: Forbidden
  #          content:
  #            application/json:
  #              schema:
  #                description: Пользователь не имеет права доступа к этому опросу
  #                type: string
  #        404:
  #          description: Not Found
  #        409:
  #          description: Conflict
  #          content:
  #            application/json:
  #              schema:
  #                description: Объявление с опросом еще не опубликовано
  #                type: string
  #                        
  /survey/get-details:
    get:
      operationId: getSurveyDetails
      summary: Получить детали выбранного опроса
      tags: [ Опрос ]
      requestBody:
        content:
          application/json:
            schema:
              $ref: './schemas/survey-schemas.yaml#/components/schemas/questionIdentifierDto'
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                $ref: './schemas/survey-schemas.yaml#/components/schemas/surveyDetailsDto'
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: './schemas/common-schemas.yaml#/components/schemas/incorrectIdentifierFormat'
        403:
          description: Forbidden
          content:
            application/json:
              schema:
                description: Пользователь не имеет права получать детали этого опроса
                type: string
                nullable: false
        404:
          description: Not Found
        409:
          description: Conflict
          content:
            application/json:
              schema:
                description: Объявление с опросом еще не опубликовано
                type: string
  
  /survey/close-survey:
    post:
      operationId: closeSurvey
      description: Закрыть опрос
      tags: [ Опрос ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './schemas/survey-schemas.yaml#/components/schemas/surveyIdentifierDto'
      responses:
        200:
          description: Ok
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: './schemas/common-schemas.yaml#/components/schemas/incorrectIdentifierFormat'
        403:
          description: Forbidden
          content:
            application/json:
              schema:
                description: Пользователь не имеет права закрыть этот опрос
                type: string
        404:
          description: Not Found
        409:
          description: Conflict
          content:
            application/json:
              schema:
                oneOf:
                  - description: Опрос уже закрыт
                    type: string
                  - description: Объявление с опросом еще не опубликовано
                    type: string
  
  
  /survey/get-results:
    get:
      operationId: getSurveysResults
      description: Получить результаты опроса
      tags: [ Опрос ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './schemas/survey-schemas.yaml#/components/schemas/surveyIdentifierDto'
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                $ref: './schemas/survey-schemas.yaml#/components/schemas/surveyResultsDto'
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: './schemas/common-schemas.yaml#/components/schemas/incorrectIdentifierFormat'
        403:
          description: Forbidden
          content:
            application/json:
              schema:
                description: Пользователь не имеет права получить результаты этого опроса
                type: string
        404:
          description: Not Found
        409:
          description: Conflict
          content:
            application/json:
              schema:
                oneOf:
                  - description: Объявление с этим опросом еще не опубликовано
                    type: string
  
  /survey/download-results:
    get:
      operationId: downloadSurveyResults
      description: Скачать результаты опроса
      tags: [ Опрос ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './schemas/survey-schemas.yaml#/components/schemas/surveyIdentifierDto'
      responses:
        200:
          description: Ok
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: './schemas/common-schemas.yaml#/components/schemas/incorrectIdentifierFormat'
        403:
          description: Forbidden
          content:
            application/json:
              schema:
                description: Пользователь не имеет права выгрузить результаты этого опроса
                type: string
        404:
          description: Not Found
        409:
          description: Conflict
          content:
            application/json:
              schema:
                oneOf:
                  - description: Объявление с этим опросом еще не опубликовано
                    type: string
  
  # question
  /question/vote:
    post:
      operationId: voteInQuestion
      summary: Проголосовать в вопросе
      tags: [ Вопрос ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './schemas/survey-schemas.yaml#/components/schemas/voteInSurveyDto'
      responses: # todo перевести текст в enum
        200:
          description: Ok
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: './schemas/common-schemas.yaml#/components/schemas/incorrectIdentifierFormat'
        403:
          description: Forbidden
          content:
            application/json:
              schema:
                description: Пользователь не имеет права голосовать в этом опросе
                type: string
        404:
          description: Not Found
          content:
            application/json:
              schema:
                oneOf:
                  - description: Вопроса с указанным идентификатором не существует
                    type: string
                  - description: Варианта ответа с указанным идентификатором не существует
                    type: string
        409:
          description: Conflict
          content:
            application/json:
              schema:
                oneOf:
                  - description: Опрос закрыт
                    type: string
                  - description: Объявление с опросом еще не опубликовано
                    type: string
                  - description: Голос за вопрос уже отдан
                    type: string
                  - description: В вопросе с единственным выбором нельзя выбрать несколько вариантов ответов
                    type: string
                  - description: Перечисленные варианты ответов относятся к разным вопросам
                    type: string
  
  /question/cancel-vote:
    post:
      operationId: cancelVoteInQuestion
      description: Отменить голос в вопросе
      tags: [ Вопрос ]
      requestBody:
        content:
          application/json:
            schema:
              $ref: './schemas/survey-schemas.yaml#/components/schemas/questionIdentifierDto'
      responses: # todo перевести текст в enum
        200:
          description: Ok
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: './schemas/common-schemas.yaml#/components/schemas/incorrectIdentifierFormat'
        403:
          description: Forbidden
          content:
            application/json:
              schema:
                description: Пользователь не имеет права голосовать в этом опросе
                type: string
        404:
          description: Not Found
        409:
          description: Conflict
          content:
            application/json:
              schema:
                oneOf:
                  - description: Опрос закрыт
                    type: string
                  - description: Пользователь не проголосовал в вопросе
                    type: string
