openapi: 3.0.3
info:
  title: API Шлюз. Опросы
  description: API шлюза управления опросами
  version: 0.0.1
servers:
  - url: 'https://localhost:8080'
paths:
  /surveys/get-details:
    get:
      operationId: getSurveyDetails
      summary: Получение деталей опроса
      responses:
        200:
          description: ok
