/*
 * Ping
 *
 * Проверка доступности сервиса
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

using BulletInBoardServer.Controllers.PingController.Attributes;
using Microsoft.AspNetCore.Mvc;

namespace BulletInBoardServer.Controllers.PingController.Controllers
{ 
    /// <summary>
    /// Контроллер проверки работоспособности сервера
    /// </summary>
    [ApiController]
    public abstract class PingApiController : ControllerBase
    { 
        /// <summary>
        /// Проверка работоспособности сервера
        /// </summary>
        /// <response code="200">Ok</response>
        [HttpGet]
        [Route("/api/ping")]
        [ValidateModelState]
        [ProducesResponseType(statusCode: 200, type: typeof(string))]
        public abstract IActionResult Ping();
    }
}
