/*
 * API Шлюз. Опросы
 *
 * API шлюза для управления опросами
 *
 * The version of the OpenAPI document: 0.0.2
 *
 * Generated by: https://openapi-generator.tech
 */

using System.ComponentModel;
using System.Runtime.Serialization;
using BulletInBoardServer.Controllers.SurveysController.Converters;
using Newtonsoft.Json;

namespace BulletInBoardServer.Controllers.SurveysController.Models
{ 
        /// <summary>
        /// Ответы:   votingForbidden - Пользователь не имеет права голосовать в этом опросе   questionDoesNotExist - Вопрос не существует   surveyClosed - Опрос закрыт   surveyNotVoted - Пользователь не проголосовал в вопросе 
        /// </summary>
        /// <value>Ответы:   votingForbidden - Пользователь не имеет права голосовать в этом опросе   questionDoesNotExist - Вопрос не существует   surveyClosed - Опрос закрыт   surveyNotVoted - Пользователь не проголосовал в вопросе </value>
        [TypeConverter(typeof(CustomEnumConverter<CancelVoteInQuestionResponses>))]
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum CancelVoteInQuestionResponses
        {
            
            /// <summary>
            /// Enum VotingForbidden for votingForbidden
            /// </summary>
            [EnumMember(Value = "votingForbidden")]
            VotingForbidden = 1,
            
            /// <summary>
            /// Enum QuestionDoesNotExist for questionDoesNotExist
            /// </summary>
            [EnumMember(Value = "questionDoesNotExist")]
            QuestionDoesNotExist = 2,
            
            /// <summary>
            /// Enum SurveyClosed for surveyClosed
            /// </summary>
            [EnumMember(Value = "surveyClosed")]
            SurveyClosed = 3,
            
            /// <summary>
            /// Enum SurveyNotVoted for surveyNotVoted
            /// </summary>
            [EnumMember(Value = "surveyNotVoted")]
            SurveyNotVoted = 4
        }
}
