/*
 * API Шлюз. Опросы
 *
 * API шлюза для управления опросами
 *
 * The version of the OpenAPI document: 0.0.2
 *
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;

namespace BulletInBoardServer.Controllers.SurveysController.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public class CreateSurveyDto : IEquatable<CreateSurveyDto>
    {
        /// <summary>
        /// Вопросы опроса
        /// </summary>
        /// <value>Вопросы опроса</value>
        [DataMember(Name="questions", EmitDefaultValue=false)]
        public List<CreateQuestionDto> Questions { get; set; }

        /// <summary>
        /// Анонимен ли опрос
        /// </summary>
        /// <value>Анонимен ли опрос</value>
        [DataMember(Name="isAnonymous", EmitDefaultValue=true)]
        public bool IsAnonymous { get; set; }

        /// <summary>
        /// Срок окончания голосования. Null, если голосование не ограничено по сроку
        /// </summary>
        /// <value>Срок окончания голосования. Null, если голосование не ограничено по сроку</value>
        [DataMember(Name="voteUntil", EmitDefaultValue=true)]
        public DateTime? VoteUntil { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CreateSurveyDto {\n");
            sb.Append("  Questions: ").Append(Questions).Append("\n");
            sb.Append("  IsAnonymous: ").Append(IsAnonymous).Append("\n");
            sb.Append("  VoteUntil: ").Append(VoteUntil).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((CreateSurveyDto)obj);
        }

        /// <summary>
        /// Returns true if CreateSurveyDto instances are equal
        /// </summary>
        /// <param name="other">Instance of CreateSurveyDto to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CreateSurveyDto other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Questions == other.Questions ||
                    Questions != null &&
                    other.Questions != null &&
                    Questions.SequenceEqual(other.Questions)
                ) && 
                (
                    IsAnonymous == other.IsAnonymous ||
                    
                    IsAnonymous.Equals(other.IsAnonymous)
                ) && 
                (
                    VoteUntil == other.VoteUntil ||
                    VoteUntil != null &&
                    VoteUntil.Equals(other.VoteUntil)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Questions != null)
                    hashCode = hashCode * 59 + Questions.GetHashCode();
                    
                    hashCode = hashCode * 59 + IsAnonymous.GetHashCode();
                    if (VoteUntil != null)
                    hashCode = hashCode * 59 + VoteUntil.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(CreateSurveyDto left, CreateSurveyDto right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(CreateSurveyDto left, CreateSurveyDto right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
