/*
 * API Шлюз. Опросы
 *
 * API шлюза для управления опросами
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

using System.ComponentModel;
using System.Runtime.Serialization;
using BulletInBoardServer.Controllers.SurveysController.Converters;
using Newtonsoft.Json;

namespace BulletInBoardServer.Controllers.SurveysController.Models
{ 
        /// <summary>
        /// Ответы:   fileTypeNotSupported - Тип файла с результатами опроса не поддерживается   surveyResultsDownloadingForbidden - Пользователь не имеет права выгрузить результаты этого опроса   surveyDoesNotExist - Опрос не существует   announcementWithSurveyNotYetPublished - Объявление с опросом еще не опубликовано 
        /// </summary>
        /// <value>Ответы:   fileTypeNotSupported - Тип файла с результатами опроса не поддерживается   surveyResultsDownloadingForbidden - Пользователь не имеет права выгрузить результаты этого опроса   surveyDoesNotExist - Опрос не существует   announcementWithSurveyNotYetPublished - Объявление с опросом еще не опубликовано </value>
        [TypeConverter(typeof(CustomEnumConverter<DownloadSurveyResultsResponses>))]
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum DownloadSurveyResultsResponses
        {
            
            /// <summary>
            /// Enum FileTypeNotSupported for fileTypeNotSupported
            /// </summary>
            [EnumMember(Value = "fileTypeNotSupported")]
            FileTypeNotSupported = 1,
            
            /// <summary>
            /// Enum SurveyResultsDownloadingForbidden for surveyResultsDownloadingForbidden
            /// </summary>
            [EnumMember(Value = "surveyResultsDownloadingForbidden")]
            SurveyResultsDownloadingForbidden = 2,
            
            /// <summary>
            /// Enum SurveyDoesNotExist for surveyDoesNotExist
            /// </summary>
            [EnumMember(Value = "surveyDoesNotExist")]
            SurveyDoesNotExist = 3,
            
            /// <summary>
            /// Enum AnnouncementWithSurveyNotYetPublished for announcementWithSurveyNotYetPublished
            /// </summary>
            [EnumMember(Value = "announcementWithSurveyNotYetPublished")]
            AnnouncementWithSurveyNotYetPublished = 4
        }
}
