/*
 * API Шлюз. Опросы
 *
 * API шлюза для управления опросами
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;

namespace BulletInBoardServer.Controllers.SurveysController.Models
{ 
    /// <summary>
    /// DTO для голосования в вопросе опроса
    /// </summary>
    [DataContract]
    public class VoteInQuestionDto : IEquatable<VoteInQuestionDto>
    {
        /// <summary>
        /// Идентификатор вопроса
        /// </summary>
        /// <value>Идентификатор вопроса</value>
        [DataMember(Name="questionId", EmitDefaultValue=false)]
        public Guid QuestionId { get; set; }

        /// <summary>
        /// Массив идентификаторов вариантов ответов
        /// </summary>
        /// <value>Массив идентификаторов вариантов ответов</value>
        [DataMember(Name="answerIds", EmitDefaultValue=false)]
        public List<Guid> AnswerIds { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class VoteInQuestionDto {\n");
            sb.Append("  QuestionId: ").Append(QuestionId).Append("\n");
            sb.Append("  AnswerIds: ").Append(AnswerIds).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((VoteInQuestionDto)obj);
        }

        /// <summary>
        /// Returns true if VoteInQuestionDto instances are equal
        /// </summary>
        /// <param name="other">Instance of VoteInQuestionDto to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(VoteInQuestionDto other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    QuestionId == other.QuestionId ||
                    QuestionId != null &&
                    QuestionId.Equals(other.QuestionId)
                ) && 
                (
                    AnswerIds == other.AnswerIds ||
                    AnswerIds != null &&
                    other.AnswerIds != null &&
                    AnswerIds.SequenceEqual(other.AnswerIds)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (QuestionId != null)
                    hashCode = hashCode * 59 + QuestionId.GetHashCode();
                    if (AnswerIds != null)
                    hashCode = hashCode * 59 + AnswerIds.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(VoteInQuestionDto left, VoteInQuestionDto right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(VoteInQuestionDto left, VoteInQuestionDto right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
