/*
 * API Шлюз. Опросы
 *
 * API шлюза для управления опросами
 *
 * The version of the OpenAPI document: 0.0.2
 *
 * Generated by: https://openapi-generator.tech
 */

using System.ComponentModel;
using System.Runtime.Serialization;
using BulletInBoardServer.Controllers.SurveysController.Converters;
using Newtonsoft.Json;

namespace BulletInBoardServer.Controllers.SurveysController.Models
{ 
        /// <summary>
        /// Ответы:    votingForbidden - Пользователь не имеет права голосовать в опросе   surveyDoesNotExist - Опрос не существует   questionDoesNotExist - Вопрос не существует   answerDoesNotExist - Вариант ответа не существует   surveyClosed - Опрос закрыт   announcementWithSurveyNotYetPublished - Объявление с опросом еще не опубликовано   surveyAlreadyVoted - Голос в опросе уже отдан   cannotSelectMultipleAnswersInSingleChoiceQuestion - В вопросе с единственным выбором нельзя выбрать несколько вариантов ответов   selectedQuestionsBelongToDifferentSurveys - Перечисленные вопросы относятся к разным опросам   selectedAnswersBelongToDifferentQuestions - Перечисленные варианты ответов относятся к разным вопросам 
        /// </summary>
        /// <value>Ответы:    votingForbidden - Пользователь не имеет права голосовать в опросе   surveyDoesNotExist - Опрос не существует   questionDoesNotExist - Вопрос не существует   answerDoesNotExist - Вариант ответа не существует   surveyClosed - Опрос закрыт   announcementWithSurveyNotYetPublished - Объявление с опросом еще не опубликовано   surveyAlreadyVoted - Голос в опросе уже отдан   cannotSelectMultipleAnswersInSingleChoiceQuestion - В вопросе с единственным выбором нельзя выбрать несколько вариантов ответов   selectedQuestionsBelongToDifferentSurveys - Перечисленные вопросы относятся к разным опросам   selectedAnswersBelongToDifferentQuestions - Перечисленные варианты ответов относятся к разным вопросам </value>
        [TypeConverter(typeof(CustomEnumConverter<VoteInSurveyResponses>))]
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum VoteInSurveyResponses
        {
            
            /// <summary>
            /// Enum VotingForbidden for votingForbidden
            /// </summary>
            [EnumMember(Value = "votingForbidden")]
            VotingForbidden = 1,
            
            /// <summary>
            /// Enum SurveyDoesNotExist for surveyDoesNotExist
            /// </summary>
            [EnumMember(Value = "surveyDoesNotExist")]
            SurveyDoesNotExist = 2,
            
            /// <summary>
            /// Enum QuestionDoesNotExist for questionDoesNotExist
            /// </summary>
            [EnumMember(Value = "questionDoesNotExist")]
            QuestionDoesNotExist = 3,
            
            /// <summary>
            /// Enum AnswerDoesNotExist for answerDoesNotExist
            /// </summary>
            [EnumMember(Value = "answerDoesNotExist")]
            AnswerDoesNotExist = 4,
            
            /// <summary>
            /// Enum SurveyClosed for surveyClosed
            /// </summary>
            [EnumMember(Value = "surveyClosed")]
            SurveyClosed = 5,
            
            /// <summary>
            /// Enum AnnouncementWithSurveyNotYetPublished for announcementWithSurveyNotYetPublished
            /// </summary>
            [EnumMember(Value = "announcementWithSurveyNotYetPublished")]
            AnnouncementWithSurveyNotYetPublished = 6,
            
            /// <summary>
            /// Enum AnswerAlreadyVoted for answerAlreadyVoted
            /// </summary>
            [EnumMember(Value = "answerAlreadyVoted")]
            AnswerAlreadyVoted = 7,
            
            /// <summary>
            /// Enum CannotSelectMultipleAnswersInSingleChoiceQuestion for cannotSelectMultipleAnswersInSingleChoiceQuestion
            /// </summary>
            [EnumMember(Value = "cannotSelectMultipleAnswersInSingleChoiceQuestion")]
            CannotSelectMultipleAnswersInSingleChoiceQuestion = 8,
            
            /// <summary>
            /// Enum SelectedQuestionsBelongToDifferentSurveys for selectedQuestionsBelongToDifferentSurveys
            /// </summary>
            [EnumMember(Value = "selectedQuestionsBelongToDifferentSurveys")]
            SelectedQuestionsBelongToDifferentSurveys = 9,
            
            /// <summary>
            /// Enum SelectedAnswersBelongToDifferentQuestions for selectedAnswersBelongToDifferentQuestions
            /// </summary>
            [EnumMember(Value = "selectedAnswersBelongToDifferentQuestions")]
            SelectedAnswersBelongToDifferentQuestions = 10
        }
}
